### ISSUE TITLE
system-bridge cannot be built using node 17

### ISSUE THREAD

**Issue by zhulik** [timmo001/system-bridge#1154]
### Description

Hello,

I'm trying to update the [system-bridge AUR package](https://aur.archlinux.org/packages/system-bridge/) and found out that `yarn package` fails, see logs.

### What Platform / OS are you running?

Linux

### What version are you running?

2.8.0

### Anything in the logs or a references that might be useful?

```txt
Successfully installed systembridgegui-0.0.0
65 INFO: PyInstaller: 4.7
65 INFO: Python: 3.9.9
67 INFO: Platform: Linux-5.15.6-zen2-1-zen-x86_64-with-glibc2.33
68 INFO: UPX is not available.
288 INFO: Determining a mapping of distributions to packages...
46955 INFO: Packages required by PySide6:
['shiboken6']
47054 INFO: Packages required by systembridge:
['aiohttp', 'websockets']
47083 INFO: Packages required by websockets:
[]
47083 INFO: Extending PYTHONPATH with paths
['/home/user/system-bridge/src/system-bridge-2.8.0']
47164 INFO: checking Analysis
47179 INFO: Appending 'binaries' from .spec
47180 INFO: Appending 'datas' from .spec
47212 INFO: checking PYZ
47212 INFO: checking PKG
47212 INFO: Bootloader /home/user/.local/lib/python3.9/site-packages/PyInstaller/bootloader/Linux-64bit-intel/run
47212 INFO: checking EXE
47214 INFO: checking COLLECT
47234 INFO: Removing dir /home/user/system-bridge/src/system-bridge-2.8.0/gui/dist/system-bridge-gui
47348 INFO: Building COLLECT COLLECT-00.toc
47974 INFO: Building COLLECT COLLECT-00.toc completed successfully.
Package.. [ undefined ]
> pkg@5.5.1
> Error! No available node version satisfies 'node17'
/home/user/system-bridge/src/system-bridge-2.8.0/node_modules/pkg-fetch/lib-es5/log.js:96
        var _this = _super !== null && _super.apply(this, arguments) || this;
                                              ^

Error [ReportedError]: No available node version satisfies 'node17'
    at new ReportedError (/home/user/system-bridge/src/system-bridge-2.8.0/node_modules/pkg-fetch/lib-es5/log.js:96:47)
    at wasReported (/home/user/system-bridge/src/system-bridge-2.8.0/node_modules/pkg-fetch/lib-es5/log.js:107:25)
    at /home/user/system-bridge/src/system-bridge-2.8.0/node_modules/pkg-fetch/lib-es5/index.js:151:53
    at step (/home/user/system-bridge/src/system-bridge-2.8.0/node_modules/pkg-fetch/lib-es5/index.js:52:23)
    at Object.next (/home/user/system-bridge/src/system-bridge-2.8.0/node_modules/pkg-fetch/lib-es5/index.js:33:53)
    at /home/user/system-bridge/src/system-bridge-2.8.0/node_modules/pkg-fetch/lib-es5/index.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (/home/user/system-bridge/src/system-bridge-2.8.0/node_modules/pkg-fetch/lib-es5/index.js:23:12)
    at need (/home/user/system-bridge/src/system-bridge-2.8.0/node_modules/pkg-fetch/lib-es5/index.js:121:12)
    at needWithDryRun (/home/user/system-bridge/src/system-bridge-2.8.0/node_modules/pkg/lib-es5/index.js:121:47) {
  wasReported: true
}

Node.js v17.2.0
error Command failed with exit code 1.
```

**Comment by timmo001** [comment]
This is a [pkg](https://github.com/vercel/pkg) specific issue. There is already an issue open for this:

https://github.com/vercel/pkg/issues/1364
