### ISSUE TITLE
No version works anymore. 

### ISSUE THREAD

**Issue by VNRARA** [timmo001/system-bridge#1164]
### Description

No version works now (v2.8.0)

### What Platform / OS are you running?

Windows

### What version are you running?

v2.8.0

### Anything in the logs or a references that might be useful?

```txt
2021-12-16 02:51:09 info: System Bridge 2.8.0: C:\Users\LNDN\AppData\Local\System Bridge - C:\Users\LNDN\AppData\Local\System Bridge\system-bridge.exe - C:\Users\LNDN\AppData\Local\System Bridge - ["C:\\Users\\LNDN\\AppData\\Local\\System Bridge\\system-bridge.exe","C:\\snapshot\\system-bridge\\dist\\index.js"] -  -  -  -
2021-12-16 02:51:09 info: Process Manager - PATH_API: C:\snapshot\system-bridge\dist\components\api\index.js
2021-12-16 02:51:09 info: Process Manager - Starting api - ["C:\\Users\\LNDN\\AppData\\Local\\System Bridge\\system-bridge.exe","C:\\snapshot\\system-bridge\\dist\\components\\api\\index.js"]
(node:28544) UnhandledPromiseRejectionWarning: DriverPackageNotInstalledError: SQLite package has not been found installed. Try to install it: npm install better-sqlite3 --save
    at DriverPackageNotInstalledError.TypeORMError [as constructor] (C:\snapshot\system-bridge\node_modules\typeorm\error\TypeORMError.js:9:28)
    at new DriverPackageNotInstalledError (C:\snapshot\system-bridge\node_modules\typeorm\error\DriverPackageNotInstalledError.js:12:23)
    at BetterSqlite3Driver.loadDependencies (C:\snapshot\system-bridge\node_modules\typeorm\driver\better-sqlite3\BetterSqlite3Driver.js:107:19)
    at new BetterSqlite3Driver (C:\snapshot\system-bridge\node_modules\typeorm\driver\better-sqlite3\BetterSqlite3Driver.js:29:15)
    at DriverFactory.create (C:\snapshot\system-bridge\node_modules\typeorm\driver\DriverFactory.js:47:24)
    at new Connection (C:\snapshot\system-bridge\node_modules\typeorm\connection\Connection.js:53:59)
    at ConnectionManager.create (C:\snapshot\system-bridge\node_modules\typeorm\connection\ConnectionManager.js:62:26)
    at C:\snapshot\system-bridge\node_modules\typeorm\globals.js:70:66
    at step (C:\snapshot\system-bridge\node_modules\tslib\tslib.js:143:27)
    at Object.next (C:\snapshot\system-bridge\node_modules\tslib\tslib.js:124:57)
(Use `system-bridge --trace-warnings ...` to show where the warning was created)
(node:28544) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:28544) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:28544) UnhandledPromiseRejectionWarning: Error: The specified module could not be found.
C:\Users\LNDN\AppData\Local\Temp\pkg\980b1b53ae99e6976c216cb102d3ffc4683250a2d0c3cfe103d71fa421a09849\node-hide-console-window\build\Release\node-hide-console-window.node
    at process.dlopen (pkg/prelude/bootstrap.js:2114:28)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at Module.require (pkg/prelude/bootstrap.js:1719:31)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (C:\snapshot\system-bridge\node_modules\node-hide-console-window\index.js:1:98)
    at Module._compile (pkg/prelude/bootstrap.js:1794:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
(node:28544) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
pkg/prelude/bootstrap.js:1740
      throw error;
      ^

Error: The specified module could not be found.
C:\Users\LNDN\AppData\Local\Temp\pkg\d10ed51a85db37e207dfe87a06a71e707f11f9dc6bb7ee15224d9828d3b4e3ed\win-audio\build\Release\audio.node
    at process.dlopen (pkg/prelude/bootstrap.js:2114:28)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at Module.require (pkg/prelude/bootstrap.js:1719:31)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (C:\snapshot\system-bridge\node_modules\win-audio\dist\index.js:5:13)
    at Module._compile (pkg/prelude/bootstrap.js:1794:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10) {
  code: 'ERR_DLOPEN_FAILED'
}
2021-12-16 02:51:10 error: Process Manager - api: Exited with code: 1
2021-12-16 02:51:10 info: Process Manager - api: Restarting in 10 seconds..
```
```


### Additional information

_No response_

**Comment by VNRARA** [comment]
Had to clean a specific temp folder i guess
