### ISSUE TITLE
Tray/GUI not working on Linux

### ISSUE THREAD

**Issue by julianrinaldi** [timmo001/system-bridge#1165]
### Description

There is no longer a tray icon. From the release notes, it looks like the system tray may have been removed purposefully. If that is the case, how do we access the settings now?

### What Platform / OS are you running?

Linux

### What version are you running?

2.8

**Comment by timmo001** [comment]
There should be. The release notes might be a bit misleading, what has changed is that the frontend is now written in Qt (Python).

Can you add any relevant logs from `/home/user/.local/system-bridge/system-bridge.log` (I beleive this is the path in linux)?

**Comment by julianrinaldi** [comment]
Here are my logs.

```
2021-12-16 10:48:29 info: System Bridge 2.8.0: /usr/local/share/system-bridge - /usr/local/share/system-bridge/system-bridge - /usr/local/share/system-bridge - ["/usr/local/share/system-bridge/system-bridge","/snapshot/system-bridge/dist/index.js"] -  -  -  - 
2021-12-16 10:48:29 info: Process Manager - PATH_API: /snapshot/system-bridge/dist/components/api/index.js
2021-12-16 10:48:29 info: Process Manager - Starting api - ["/usr/local/share/system-bridge/system-bridge","/snapshot/system-bridge/dist/components/api/index.js"]
2021-12-16 10:48:29 info: Process Manager - PATH_GUI_PACKAGED: /usr/local/share/system-bridge/system-bridge-gui/system-bridge-gui
2021-12-16 10:48:29 info: Process Manager - Starting gui - ["/usr/local/share/system-bridge/system-bridge-gui/system-bridge-gui","--host","localhost","--api-key","***","--api-port","9170","--frontend-port","9170","--log-level","info","--websocket-port","9172"]
2021-12-16 10:48:29 error: Process Manager - gui: Exited with code: 1
2021-12-16 10:48:29 info: Process Manager - gui: Restarting in 10 seconds..
2021-12-16 10:48:31 info: API - /usr/local/share/system-bridge - /usr/local/share/system-bridge/system-bridge - /usr/local/share/system-bridge - ["/usr/local/share/system-bridge/system-bridge","/snapshot/system-bridge/dist/components/api/index.js"] -  -  -  - 
2021-12-16 10:48:32 error: API - Uncaught Exception: Error: getaddrinfo -3008
2021-12-16 10:48:32 error: API - Uncaught Exception: Error: getaddrinfo -3008
2021-12-16 10:48:32 error: API - Uncaught Exception: Error: getaddrinfo -3008
2021-12-16 10:48:32 error: API - Uncaught Exception: Error: getaddrinfo -3008
2021-12-16 10:48:32 error: API - Uncaught Exception: Error: getaddrinfo -3008
2021-12-16 10:48:32 error: API - Uncaught Exception: Error: getaddrinfo -3008
2021-12-16 10:48:32 error: API - Uncaught Exception: Error: getaddrinfo -3008
2021-12-16 10:48:32 error: API - Uncaught Exception: Error: getaddrinfo -3008
2021-12-16 10:48:32 error: API - Uncaught Exception: Error: getaddrinfo -3008
2021-12-16 10:48:32 error: API - Uncaught Exception: Error: getaddrinfo -3008
2021-12-16 10:48:32 error: API - Uncaught Exception: Error: getaddrinfo -3008
2021-12-16 10:48:32 error: API - Uncaught Exception: Error: getaddrinfo -3008
2021-12-16 10:48:32 error: API - Uncaught Exception: Error: getaddrinfo -3008
2021-12-16 10:48:32 error: API - Uncaught Exception: Error: getaddrinfo -3008
2021-12-16 10:48:32 info: API - API started on port 9170
2021-12-16 10:48:39 info: Process Manager - PATH_GUI_PACKAGED: /usr/local/share/system-bridge/system-bridge-gui/system-bridge-gui
2021-12-16 10:48:39 info: Process Manager - Starting gui - ["/usr/local/share/system-bridge/system-bridge-gui/system-bridge-gui","--host","localhost","--api-key","***","--api-port","9170","--frontend-port","9170","--log-level","info","--websocket-port","9172"]
2021-12-16 10:48:40 error: Process Manager - gui: Exited with code: 1
2021-12-16 10:48:40 info: Process Manager - gui: Restarting in 10 seconds..
2021-12-16 10:48:50 info: Process Manager - PATH_GUI_PACKAGED: /usr/local/share/system-bridge/system-bridge-gui/system-bridge-gui
2021-12-16 10:48:50 info: Process Manager - Starting gui - ["/usr/local/share/system-bridge/system-bridge-gui/system-bridge-gui","--host","localhost","--api-key","***","--api-port","9170","--frontend-port","9170","--log-level","info","--websocket-port","9172"]
2021-12-16 10:48:50 error: Process Manager - gui: Exited with code: 1
2021-12-16 10:48:50 info: Process Manager - gui: Restarting in 10 seconds..
```

**Comment by timmo001** [comment]
Latest version:

```bash
2022-01-01 18:07:35 info: System Bridge 2.8.1: /usr/local/share/system-bridge - /usr/local/share/system-bridge/system-bridge - /home/aidan - ["/usr/local/share/system-bridge/system-bridge","/snapshot/system-bridge/dist/index.js"] -  -  -  - 
2022-01-01 18:07:35 info: Process Manager - PATH_API: /snapshot/system-bridge/dist/components/api/index.js
2022-01-01 18:07:35 info: Process Manager - Starting api - ["/usr/local/share/system-bridge/system-bridge","/snapshot/system-bridge/dist/components/api/index.js"]
2022-01-01 18:07:35 info: Process Manager - PATH_GUI_PACKAGED: /usr/local/share/system-bridge/system-bridge-gui/system-bridge-gui
2022-01-01 18:07:35 info: Process Manager - Starting gui - ["/usr/local/share/system-bridge/system-bridge-gui/system-bridge-gui","--host","localhost","--api-key","***","--api-port","9170","--frontend-port","9170","--log-level","info","--websocket-port","9172"]
Traceback (most recent call last):
  File "gui/__init__.py", line 5, in <module>
  File "/home/runner/.local/lib/python3.8/site-packages/systembridgegui/main.py", line 20, in <module>
  File "/home/runner/.local/lib/python3.8/site-packages/systembridgegui/system_tray.py", line 25, in <module>
  File "/home/runner/.local/lib/python3.8/site-packages/systembridgegui/system_tray.py", line 34, in SystemTray
TypeError: 'ABCMeta' object is not subscriptable
[2521] Failed to execute script '__init__' due to unhandled exception!
2022-01-01 18:07:37 error: Process Manager - gui: Exited with code: 1
```

**Comment by CallMeShark** [comment]
I am currently having the same issue. System-bridge is running but I cannot open the GUI to access the settings. Is there a way to find my API key or update my MQTT broker info without the GUI?

**Comment by timmo001** [comment]
Fixed in updated https://github.com/timmo001/workflows

**Comment by MostHated** [comment]
Unfortunately, same issue here.

![](https://i.imgur.com/qPzN3d6.png)
