### ISSUE TITLE
GUI doesn't launch on first launch (fresh install)

### ISSUE THREAD

**Issue by jackyaz** [timmo001/system-bridge#1254]
### Description

New user, downloaded the 2.8.2 release setup exe and installed it. Launched via desktop shortcut and...nothing happens
Checking the log shows 
```
2022-01-18 12:17:43 warn: API Execption - HTTP Exception: {"status":503,"body":{},"message":"Http Exception","path":"/information"}
```
followed by a nevr ending repeat of
```
2022-01-18 12:18:55 info: Process Manager - Starting gui - ["C:\\Users\\Jack\\AppData\\Local\\System Bridge\\system-bridge-gui\\system-bridge-gui.exe","--host","localhost","--api-key","***","--api-port","9170","--frontend-port","9170","--log-level","info","--websocket-port","9172"]
2022-01-18 12:18:56 info: RequestInterceptor - GET: /information - 200
2022-01-18 12:18:59 error: Process Manager - gui: Exited with code: 1
2022-01-18 12:18:59 info: Process Manager - gui: Restarting in 10 seconds..
``` 
Did i miss a step somewhere?

### What Platform / OS are you running?

Windows 10

### What version are you running?

2.8.2

**Comment by jackyaz** [comment]
I noticed this:
```
Starting api - ["C:\\Users\\Jack\\AppData\\Local\\System Bridge\\system-bridge.exe","C:\\snapshot\\system-bridge\\dist\\components\\api\\index.js"]
```
The latter path doesn't exist on my system. Something dragged in by mistake during last build/release?

**Comment by jackyaz** [comment]
Restarting after killing the process hasn't helped either :(

**Comment by jackyaz** [comment]
Just an update, I tried deleting both folders in local and roaming appdata, then reinstalling, and still can't get the GUI to open at all

**Comment by jackyaz** [comment]
2.8.1 and 2.8.0 also failed, 2.7.8 works. Must be something about Qt that my computer doesn't like

**Comment by jackyaz** [comment]
Manually launching 2.8.2 gui with debug logging provides:
```
2022-01-18 22:36:42 DEBUG (MainThread) [SystemTray] SystemTray __init__
Traceback (most recent call last):
  File "gui\__init__.py", line 63, in <module>
  File "C:\Users\atims\AppData\Local\Programs\Python\Python310\lib\site-packages\systembridgegui\main.py", line 66, in __init__
  File "C:\Users\atims\AppData\Local\Programs\Python\Python310\lib\site-packages\systembridgegui\system_tray.py", line 67, in __init__
  File "C:\Users\Jack\AppData\Local\System Bridge\system-bridge-gui\systembridge\objects\information.py", line 65, in updates
    return Updates(self.attributes.get("updates"))
AttributeError: 'str' object has no attribute 'get'
[26088] Failed to execute script '__init__' due to unhandled exception!
```

**Comment by jackyaz** [comment]
Got it to launch. In C:\Users\Jack\AppData\Local\System Bridge\system-bridge-gui\systembridge\objects\information.py I amended 
```
    @property
    def updates(self) -> Updates:
        return Updates(self.attributes.get("updates"))
```

to

```
    @property
    def updates(self) -> Updates:
        try:
            return Updates(self.attributes.get("updates"))
        except:
            return None
```

**Comment by Magic815** [comment]
I think I might have the same (or similar) issue? Installed 2.8.2 on Windows 10, using the setup exe release.

When I ran the exe, no GUI seemed to appear. After trying a second time, I saw an icon appear on my taskbar, but still no GUI appeared on my screen. If I right-click the taskbar icon and hit 'Open Settings,' I get a "500 | Internal Server Error." And if I right-click and hit 'Setup Bridges,' the 'API key' field is blank.

Any thoughts on how I most cleanly uninstall System Bridge from my Windows PC, so that I can try again with version 2.7.8?

**Comment by SynoUser-NL** [comment]
> I think I might have the same (or similar) issue? Installed 2.8.4 on Windows 10, using the setup exe release.
> 
> When I ran the exe, no GUI seemed to appear. After trying a second time, I saw an icon appear on my taskbar, but still no GUI appeared on my screen. If I right-click the taskbar icon and hit 'Open Settings,' I get a "500 | Internal Server Error." And if I right-click and hit 'Setup Bridges,' the 'API key' field is blank.
> 

Same here.. v2.8.4
When trying to add an API key the error "Error testing bridge: Request failed with status code 403" displays left of the Cancel button. When exiting the application it takes 10-15 seconds for the icon to disappear from the taskbar.
The View Data display is just a mess.. 
![image](https://user-images.githubusercontent.com/10847240/158803965-2b94394c-4b7d-4411-8255-6e2cf34822fb.png)

Just recently came across this software, so first time user. But not working at all on my system.

Also, why does this software install in a user profile by default?

Hope this software will improve soon.. keen to try out further.
Thanks!
