### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by JohannCR** [timmo001/system-bridge#1804]
### Description

After successfull install following instructions(https://system-bridge.timmo.dev/docs/install), impossible to launch service.
python -m systembridgebackend gives error

```
Traceback (most recent call last):
  File "/home/username/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/username/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/username/anaconda3/lib/python3.8/site-packages/systembridgebackend/__main__.py", line 7, in <module>
    from systembridgeshared.const import SETTING_AUTOSTART, SETTING_LOG_LEVEL
  File "/home/username/anaconda3/lib/python3.8/site-packages/systembridgeshared/const.py", line 3, in <module>
    from systembridgeshared.models.bridge import Bridge
  File "/home/username/anaconda3/lib/python3.8/site-packages/systembridgeshared/models/bridge.py", line 9, in <module>
    class Bridge(BaseModel):
  File "pydantic/main.py", line 188, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/typing.py", line 419, in pydantic.typing.resolve_annotations
    For example:
  File "/home/username/anaconda3/lib/python3.8/typing.py", line 270, in _eval_type
    return t._evaluate(globalns, localns)
  File "/home/username/anaconda3/lib/python3.8/typing.py", line 518, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
TypeError: 'type' object is not subscriptable
```

### What Platform / OS are you running?

Linux

### What version are you running?

last

**Comment by timmo001** [comment]
This may be due to python3.8 typings being different to 3.9+

Try upgrading Python

**Comment by JohannCR** [comment]
Thanks it works better, but still looooots of errors and even though there is an application shortcut, it does nothing and I've got no system tray icon...
Errors are "cannot start a transaction within a transaction" and
`Exception in thread Thread-5:
Traceback (most recent call last):
  File "/home/username/anaconda3/envs/py39/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/home/username/anaconda3/envs/py39/lib/python3.9/site-packages/systembridgebackend/data.py", line 47, in run
    asyncio.run(self._update.update_frequent_data(self._updated_callback))
  File "/home/username/anaconda3/envs/py39/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1501, in uvloop.loop.Loop.run_until_complete
  File "/home/username/anaconda3/envs/py39/lib/python3.9/site-packages/systembridgebackend/modules/update.py", line 82, in update_frequent_data
    await asyncio.gather(*tasks)
  File "/home/username/anaconda3/envs/py39/lib/python3.9/site-packages/systembridgebackend/modules/update.py", line 52, in _update
    await updated_callback(class_obj["name"])
  File "/home/username/anaconda3/envs/py39/lib/python3.9/site-packages/systembridgebackend/server/__init__.py", line 314, in _callback_data_updated
    await self._listeners.refresh_data_by_module(module)
  File "/home/username/anaconda3/envs/py39/lib/python3.9/site-packages/systembridgebackend/modules/listeners.py", line 103, in refresh_data_by_module
    self._data[module] = model(**new_data).dict()
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 8 validation errors for Cpu
count
  field required (type=value_error.missing)
frequency_current
  field required (type=value_error.missing)
frequency_max
  field required (type=value_error.missing)
stats_ctx_switches
  field required (type=value_error.missing)
last_updated -> count
  field required (type=value_error.missing)
last_updated -> frequency_current
  field required (type=value_error.missing)
last_updated -> frequency_max
  field required (type=value_error.missing)
last_updated -> stats_ctx_switches
  field required (type=value_error.missing)`

**Comment by JohannCR** [comment]
python -m systembridgecli api-key

Error executing SQL: CREATE TABLE IF NOT EXISTS secrets (key TEXT PRIMARY KEY,value TEXT,timestamp DOUBLE)
database is locked

**Comment by spike886** [comment]
I have the same error than @JohannCR. A lot of failed SQL queries with the error `cannot start a transaction within a transaction
`
and at the end other errors
```
2022-07-07 00:34:52 ERROR (Thread-3) [systembridgeshared.database.Database] Error executing SQL: INSERT INTO disk (key, value, timestamp) VALUES ('partitions_/snap/gnome-3-38-2004/106_mountpoint', '/snap/gnome-3-38-2004/106', 1657164892.1291504) ON CONFLICT(key) DO UPDATE SET value = '/snap/gnome-3-38-2004/106', timestamp = 1657164892.1291504 WHERE key = 'partitions_/snap/gnome-3-38-2004/106_mountpoint'
cannot start a transaction within a transaction
2022-07-07 00:34:52 ERROR (Thread-3) [systembridgeshared.database.Database] Error executing SQL: INSERT INTO disk (key, value, timestamp) VALUES ('partitions_/snap/gnome-3-38-2004/106_maxfile', '256', 1657164892.1384604) ON CONFLICT(key) DO UPDATE SET value = '256', timestamp = 1657164892.1384604 WHERE key = 'partitions_/snap/gnome-3-38-2004/106_maxfile'
cannot start a transaction within a transaction
2022-07-07 00:34:52 ERROR (Thread-3) [systembridgeshared.database.Database] Error executing SQL: INSERT INTO disk (key, value, timestamp) VALUES ('partitions_/snap/gnome-3-38-2004/106_maxpath', '4096', 1657164892.1406825) ON CONFLICT(key) DO UPDATE SET value = '4096', timestamp = 1657164892.1406825 WHERE key = 'partitions_/snap/gnome-3-38-2004/106_maxpath'
cannot start a transaction within a transaction
2022-07-07 00:34:53 ERROR (Thread-3) [systembridgebackend.modules.disk.Disk] PermissionError: [Errno 13] Permission denied: '/var/lib/docker/overlay2/42a9370de91f29e4ea2834bf2400286a6a99f8d851f906e7199a0bec70cf6626/merged'
2022-07-07 00:34:53 ERROR (Thread-3) [systembridgebackend.modules.disk.Disk] PermissionError: [Errno 13] Permission denied: '/var/lib/docker/overlay2/6b5558e198720d1a25b8d398b977f10a0ca320ee0a9281608760e2dae98a77d4/merged'
2022-07-07 00:34:53 ERROR (Thread-3) [systembridgebackend.modules.disk.Disk] PermissionError: [Errno 13] Permission denied: '/var/lib/docker/overlay2/985b68841993145434d0aac424589248cdd2da7cdc00e1dc3ba3b6a917a811b0/merged'
2022-07-07 00:34:53 ERROR (Thread-3) [systembridgebackend.modules.disk.Disk] PermissionError: [Errno 13] Permission denied: '/var/lib/docker/containers/c30b4e249451f2442124401135904b01829225f29fcd684e8d3d9acf1b707fa8/mounts/shm'
2022-07-07 00:34:53 ERROR (Thread-3) [systembridgebackend.modules.disk.Disk] PermissionError: [Errno 13] Permission denied: '/var/lib/docker/containers/727ca0861651fd324b1d08c4f7e45e8620d63c7765764e2858935d013a84f0da/mounts/shm'
2022-07-07 00:34:53 ERROR (Thread-3) [systembridgebackend.modules.disk.Disk] PermissionError: [Errno 13] Permission denied: '/var/lib/docker/containers/c70e81ab3a74205c84a4e9eec41a4405b67521e0322167cfab15c2c470c41fe1/mounts/shm'
2022-07-07 00:34:53 ERROR (Thread-3) [systembridgebackend.modules.disk.Disk] PermissionError: [Errno 13] Permission denied: '/run/docker/netns/34b2d5501474'
2022-07-07 00:34:53 ERROR (Thread-3) [systembridgebackend.modules.disk.Disk] PermissionError: [Errno 13] Permission denied: '/run/docker/netns/e013fa45b697'
2022-07-07 00:34:53 ERROR (Thread-3) [systembridgebackend.modules.disk.Disk] PermissionError: [Errno 13] Permission denied: '/run/docker/netns/8e3aa037291e'
2022-07-07 00:34:54 ERROR (Thread-3) [systembridgebackend.modules.disk.Disk] PermissionError: [Errno 1] Operation not permitted: '/run/user/1000/doc'
```

and after a few minutes running I have another error:
```
Exception in thread Thread-25:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/andres/.local/lib/python3.10/site-packages/systembridgebackend/data.py", line 47, in run
    asyncio.run(self._update.update_frequent_data(self._updated_callback))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1501, in uvloop.loop.Loop.run_until_complete
  File "/home/andres/.local/lib/python3.10/site-packages/systembridgebackend/modules/update.py", line 82, in update_frequent_data
    await asyncio.gather(*tasks)
  File "/home/andres/.local/lib/python3.10/site-packages/systembridgebackend/modules/update.py", line 51, in _update
    await class_obj["cls"].update_all_data()
  File "/home/andres/.local/lib/python3.10/site-packages/systembridgebackend/modules/cpu/update.py", line 100, in update_all_data
    await asyncio.gather(
  File "/home/andres/.local/lib/python3.10/site-packages/systembridgebackend/modules/cpu/update.py", line 70, in update_times_per_cpu
    self._database.write("cpu", f"times_per_cpu_{count}_{key}", value)
  File "/home/andres/.local/lib/python3.10/site-packages/systembridgeshared/database.py", line 180, in write
    self.execute_sql(
  File "/home/andres/.local/lib/python3.10/site-packages/systembridgeshared/database.py", line 59, in execute_sql
    self._connection.commit()
sqlite3.DatabaseError: no more rows available
```

but I can get the api from `python -m systembridgecli api-key`

But I can't connect from Homeassistant and I can't see the gui

**Comment by timmo001** [comment]
> Error executing SQL: CREATE TABLE IF NOT EXISTS secrets (key TEXT PRIMARY KEY,value TEXT,timestamp DOUBLE) database is locked

The above error points to another application locking the database. Make sure there are not additional python instances running. You may have to do this via your process manager

**Comment by JohannCR** [comment]
I've got loads of python scripts running left and right, if system-bridge cannot run because of that it's a problem ^^
The fact that it runs in a separate env is not enough ? Anything I can do ?

**Comment by timmo001** [comment]
Well, that database is an SQLite database located in the app data directory specifically for this app. So the only application that should be using this database, would be this one.

Check you don't have multiple instances of `systembridgebackend` running

**Comment by JohannCR** [comment]
Yes you're right, a reboot cleared that right up. Thanks
