### ISSUE TITLE
HA Plugin "Initializing" Loop

### ISSUE THREAD

**Issue by clutch70** [timmo001/system-bridge#2075]
### Description

The HASS plugin successfully detects the installation running on a given workstation, however when attempting to initialize and create sensors, the plugin reports 

"Retrying setup: Timed out waiting for IP (IP)."

These errors are accompanied by the following logs. The first was collected during initial configuration, the second was collecting during an iteration if the initialization loop.

### Anything in the logs or a references that might be useful?

```txt
2022-10-25 12:14:25 DEBUG (MainThread) [sanic.root] Dispatching signal: http.lifecycle.complete
2022-10-25 12:14:25 ERROR (Thread-6) [asyncio] Task was destroyed but it is pending!
source_traceback: Object created at (most recent call last):
  File "c:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\Program Files\Python310\lib\site-packages\systembridgebackend\__main__.py", line 54, in <module>
    Main()
  File "c:\Program Files\Python310\lib\site-packages\systembridgebackend\__main__.py", line 42, in __init__
    self._server.start_server()
  File "c:\Program Files\Python310\lib\site-packages\systembridgebackend\server\__init__.py", line 379, in start_server
    self._server.run(
  File "C:\Users\bcustard\AppData\Roaming\Python\Python310\site-packages\sanic\mixins\runner.py", line 169, in run
    self.__class__.serve(primary=self)  # type: ignore
  File "C:\Users\bcustard\AppData\Roaming\Python\Python310\site-packages\sanic\mixins\runner.py", line 672, in serve
    serve_single(primary_server_info.settings)
  File "C:\Users\bcustard\AppData\Roaming\Python\Python310\site-packages\sanic\server\runners.py", line 324, in serve_single
    serve(**server_settings)
  File "C:\Users\bcustard\AppData\Roaming\Python\Python310\site-packages\sanic\server\runners.py", line 106, in serve
    return _serve_http_1(
  File "C:\Users\bcustard\AppData\Roaming\Python\Python310\site-packages\sanic\server\runners.py", line 265, in _serve_http_1
    _run_server_forever(
  File "C:\Users\bcustard\AppData\Roaming\Python\Python310\site-packages\sanic\server\runners.py", line 151, in _run_server_forever
    loop.run_forever()
  File "c:\Program Files\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "c:\Program Files\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "c:\Program Files\Python310\lib\asyncio\base_events.py", line 1888, in _run_once
    handle._run()
  File "c:\Program Files\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "c:\Program Files\Python310\lib\site-packages\systembridgebackend\server\__init__.py", line 200, in _handler_websocket
    await websocket.handler()
  File "c:\Program Files\Python310\lib\site-packages\systembridgebackend\server\websocket.py", line 985, in handler
    await self._handler(listener_id)
  File "c:\Program Files\Python310\lib\site-packages\systembridgebackend\server\websocket.py", line 174, in _handler
    data = loads(await self._websocket.recv())
  File "C:\Users\bcustard\AppData\Roaming\Python\Python310\site-packages\sanic\server\websockets\impl.py", line 523, in recv
    asyncio.ensure_future(self.assembler.get(timeout)),
  File "c:\Program Files\Python310\lib\asyncio\tasks.py", line 615, in ensure_future
    return _ensure_future(coro_or_future, loop=loop)
  File "c:\Program Files\Python310\lib\asyncio\tasks.py", line 636, in _ensure_future
    return loop.create_task(coro_or_future)
task: <Task pending name='Task-30' coro=<WebsocketFrameAssembler.get() running at C:\Users\bcustard\AppData\Roaming\Python\Python310\site-packages\sanic\server\websockets\frame.py:117> wait_for=<Future pending cb=[Task.task_wakeup()] created at c:\Program Files\Python310\lib\asyncio\base_events.py:429> created at c:\Program Files\Python310\lib\asyncio\tasks.py:636>
2022-10-25 12:14:25 DEBUG (Thread-6) [systembridgebackend.modules.cpu.CPU] Found CPU temperature: windows_hardware_amd_ryzen_9_5950x_1_core_tctl/tdie_temperature = 0.0












Exception in thread Thread-7:
Traceback (most recent call last):
  File "c:\Program Files\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "c:\Program Files\Python310\lib\site-packages\systembridgebackend\data.py", line 47, in run
    asyncio.run(self._update.update_frequent_data(self._updated_callback))
  File "c:\Program Files\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "c:\Program Files\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "c:\Program Files\Python310\lib\site-packages\systembridgebackend\modules\update.py", line 76, in update_frequent_data
    await asyncio.gather(*tasks)
  File "c:\Program Files\Python310\lib\site-packages\systembridgebackend\modules\update.py", line 49, in _update
    await class_obj["cls"].update_all_data()
  File "c:\Program Files\Python310\lib\site-packages\systembridgebackend\modules\cpu\update.py", line 198, in update_all_data
    await asyncio.gather(
  File "c:\Program Files\Python310\lib\site-packages\systembridgebackend\modules\cpu\update.py", line 59, in update_load_average
    avg_tuple = self._cpu.load_average()
  File "c:\Program Files\Python310\lib\site-packages\systembridgebackend\modules\cpu\__init__.py", line 42, in load_average
    return getloadavg()
  File "c:\Program Files\Python310\lib\site-packages\psutil\_pswindows.py", line 347, in getloadavg
    cext.init_loadavg_counter()
RuntimeError: PdhAddEnglishCounterW failed. Performance counters may be disabled.
```

**Comment by timmo001** [comment]
Please install the [latest](https://github.com/timmo001/system-bridge/releases/latest) version and reopen if your issues still persist. Thanks
