### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by aso824** [timmo001/system-bridge#2092]
### Description

Linux Mint 20.2, Python 3.8.10:

```
$ python3 -m systembridgebackend

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/aso/.local/lib/python3.8/site-packages/systembridgebackend/__main__.py", line 6, in <module>
    from systembridgeshared.const import SETTING_AUTOSTART, SETTING_LOG_LEVEL
  File "/home/aso/.local/lib/python3.8/site-packages/systembridgeshared/const.py", line 4, in <module>
    from .models.data import Data
  File "/home/aso/.local/lib/python3.8/site-packages/systembridgeshared/models/data.py", line 16, in <module>
    from .sensors import Sensors
  File "/home/aso/.local/lib/python3.8/site-packages/systembridgeshared/models/sensors.py", line 11, in <module>
    class Sensors(BaseModel):
  File "pydantic/main.py", line 179, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/typing.py", line 399, in pydantic.typing.resolve_annotations
    """Special type construct to mark class variables.
  File "/usr/lib/python3.8/typing.py", line 270, in _eval_type
    return t._evaluate(globalns, localns)
  File "/usr/lib/python3.8/typing.py", line 518, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
TypeError: 'type' object is not subscriptable
```

Fresh installation, first run. Also, tried in venv but with same result.

### What Platform / OS are you running?

Linux

### What version are you running?

3.4.9

**Comment by aso824** [comment]
Just found that using Python 3.9 it runs. Maybe consider info in README or backward compatibility?
