### ISSUE TITLE
Empty Display data provoking crash

### ISSUE THREAD

**Issue by david-cuenca-bcn82** [timmo001/system-bridge#2098]
### Description

This is the data I have in the display module: 
{
  "last_updated": {}
}

(accessing through the browser to http://192.168.1.247:9170/app/data.html?apiKey=<my-api-key>&apiPort=9170. All other modules data look fine)

### What Platform / OS are you running?

Linux

### What version are you running?

3.4.9

### Anything in the logs or a references that might be useful?

```txt
Logger: homeassistant
Source: components/system_bridge/coordinator.py:150
First occurred: 1:32:00 AM (2 occurrences)
Last logged: 1:32:35 AM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/system_bridge/coordinator.py", line 150, in _listen_for_data
    await self.websocket_client.listen(callback=self.async_handle_module)
  File "/usr/local/lib/python3.10/site-packages/systembridgeconnector/websocket_client.py", line 492, in listen
    await self.listen_for_messages(callback=_callback_message)
  File "/usr/local/lib/python3.10/site-packages/systembridgeconnector/websocket_client.py", line 507, in listen_for_messages
    await callback(message)
  File "/usr/local/lib/python3.10/site-packages/systembridgeconnector/websocket_client.py", line 480, in _callback_message
    model(**message[EVENT_DATA]),
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 2 validation errors for Display
displays
  field required (type=value_error.missing)
last_updated -> displays
  field required (type=value_error.missing)
```

### Additional information

Running systembridge in Ubuntu 22.10 with Python version 3.10.7

**Comment by timmo001** [comment]
Fixed in https://github.com/home-assistant/core/pull/79732

**Comment by timmo001** [comment]
Also should be aided by #2103
