### ISSUE TITLE
Exception while parsing display data

### ISSUE THREAD

**Issue by cbergmann** [timmo001/system-bridge#2120]
### Description

hi,

I try to controll my windows pc from home assistant via system bridge.
I can access the api on the raspberry pi running home assistant via curl.
After adding the integration in home assistant it initializes and after some time it shows the following error:
  Timed out waiting for <IP> (<IP>).
The system bridge logs don't show anything suspicious.
The home assistant logs (shown below) show an acception with the following details:
  pydantic.error_wrappers.ValidationError: 2 validation errors for Display
When accessing http://<ip>:9170/api/data/display?apiKey=<key> I get the following result:
  {"last_updated":{}}
I don't know if this is the expected behaviour because this is an desktop machine connected to a KVM switch that (depending on the state of the KVM switch) might not have a display connected.

On the other hand I don't need the display information. It would be great if I could somehow disable modules.

I hope you can help me
Kind regards
Clemens

### What Platform / OS are you running?

Windows

### What version are you running?

3.5.0

### Anything in the logs or a references that might be useful?

```txt
2022-11-12 09:01:13.951 ERROR (MainThread) [homeassistant.components.unifi] Error connecting to the UniFi Network at unifi.bergmann.click: Error requesting data from unifi.bergmann.click: Cannot connect to host unifi.bergmann.click:443 ssl:True [SSLCertVerificationError: (1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'unifi.bergmann.click'. (_ssl.c:1123)")]
2022-11-12 09:01:55.278 WARNING (MainThread) [homeassistant.components.mqtt.light.schema_json] Invalid color mode received for entity light.lampe_eg_kueche
2022-11-12 09:02:00.888 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/system_bridge/coordinator.py", line 150, in _listen_for_data
    await self.websocket_client.listen(callback=self.async_handle_module)
  File "/srv/homeassistant/lib/python3.9/site-packages/systembridgeconnector/websocket_client.py", line 492, in listen
    await self.listen_for_messages(callback=_callback_message)
  File "/srv/homeassistant/lib/python3.9/site-packages/systembridgeconnector/websocket_client.py", line 507, in listen_for_messages
    await callback(message)
  File "/srv/homeassistant/lib/python3.9/site-packages/systembridgeconnector/websocket_client.py", line 480, in _callback_message
    model(**message[EVENT_DATA]),
  File "/srv/homeassistant/lib/python3.9/site-packages/pydantic/main.py", line 331, in __init__
    __doc__ = ''  # Null out the Representation docstring
pydantic.error_wrappers.ValidationError: 2 validation errors for Display
displays
  field required (type=value_error.missing)
last_updated -> displays
  field required (type=value_error.missing)
```

**Comment by cbergmann** [comment]
Ane additional hint might be that I start the backend as a windows task on system boot.
This is so that I don't have to log on to control the pc.
The task command is python -m systembridgebackend --no-gui

**Comment by cbergmann** [comment]
I should have looked into the closed issues.
This is a duplicate of #2098
