### ISSUE TITLE
Loop Initializing validation errors for Display

### ISSUE THREAD

**Issue by frieser** [timmo001/system-bridge#2121]
### Description

Home assistant cant connect to System Bridge, causing a loop trying to connect. Using the last version 3.5.0

error in HA: validation errors for Display. Great software by the way.

I think it was a fix in 3.5.0, but or is another bug or is the [same.](https://github.com/timmo001/system-bridge/issues/2075)

Fedora Silverblue 36 5.18.13-200.fc36.x86_64 running as root in an virtual environment

Installed with:
python -m pip install --upgrade systembridgeshared systembridgebackend systembridgecli systembridgefrontend systembridgegui

HA version: 2022.11.2

### What Platform / OS are you running?

Linux

### What version are you running?

3.5.0

### Anything in the logs or a references that might be useful?

```txt
Logs from system bridge
-----------------------

[frieser@192 ~]$ sudo su
[sudo] password for frieser: 
[root@192 frieser]# cd dev
[root@192 dev]# source ./env/bin/activate
(env) [root@192 dev]# python -m systembridgebackend --no-gui
Frontend not found: No module named 'systembridgefrontend'
2022-11-13 00:21:55 INFO (MainThread) [__main__.Main] System Bridge 3.5.0: Startup
2022-11-13 00:21:55 INFO (MainThread) [__main__.Main] Autostart enabled: False
2022-11-13 00:21:57 INFO (MainThread) [systembridgebackend.server.Server] Setup API app
2022-11-13 00:21:57 INFO (MainThread) [systembridgebackend.server.Server] Setup API server
2022-11-13 00:21:57 INFO (MainThread) [systembridgebackend.server.Server] Server initialized
2022-11-13 00:21:57 INFO (MainThread) [systembridgebackend.server.Server] Start server
2022-11-13 00:21:57 INFO (MainThread) [uvicorn.error] Started server process [48374]
2022-11-13 00:21:57 INFO (MainThread) [uvicorn.error] Waiting for application startup.
2022-11-13 00:21:57 INFO (MainThread) [systembridgebackend.server.Server] Update data
2022-11-13 00:21:57 INFO (MainThread) [systembridgebackend.server.Server] Schedule next update in 2 minutes
2022-11-13 00:21:57 INFO (Thread-2) [systembridgebackend.modules.update.Update] Update data
2022-11-13 00:21:57 INFO (MainThread) [systembridgebackend.server.Server] Update frequent data
2022-11-13 00:21:57 INFO (MainThread) [systembridgebackend.server.Server] Schedule next frequent update in 30 seconds
2022-11-13 00:21:57 INFO (Thread-3) [systembridgebackend.modules.update.Update] Update frequent data
2022-11-13 00:21:57 INFO (MainThread) [uvicorn.error] Application startup complete.
2022-11-13 00:21:57 INFO (MainThread) [uvicorn.error] Uvicorn running on http://0.0.0.0:9170 (Press CTRL+C to quit)
2022-11-13 00:21:58 INFO (Thread-3) [systembridgebackend.modules.listeners.Listeners] Refresh data by module: sensors
2022-11-13 00:21:58 INFO (Thread-3) [systembridgebackend.modules.listeners.Listeners] Data changed for module: sensors
2022-11-13 00:21:58 INFO (Thread-3) [systembridgebackend.modules.listeners.Listeners] Refresh data by module: display
2022-11-13 00:21:58 INFO (Thread-3) [systembridgebackend.modules.listeners.Listeners] Data changed for module: display
2022-11-13 00:21:58 INFO (Thread-3) [systembridgebackend.modules.listeners.Listeners] Refresh data by module: gpu
2022-11-13 00:21:58 INFO (Thread-3) [systembridgebackend.modules.listeners.Listeners] Data changed for module: gpu
2022-11-13 00:22:00 INFO (MainThread) [uvicorn.error] ('192.168.1.100', 52328) - "WebSocket /api/websocket" [accepted]
2022-11-13 00:22:00 INFO (MainThread) [uvicorn.error] connection open
2022-11-13 00:22:00 INFO (MainThread) [systembridgebackend.server.websocket.WebSocketHandler] Received: GET_DATA
2022-11-13 00:22:00 INFO (MainThread) [systembridgebackend.server.websocket.WebSocketHandler] Getting data: ['system']
2022-11-13 00:22:00 INFO (MainThread) [uvicorn.access] 192.168.1.100:52336 - "GET /information HTTP/1.1" 404
2022-11-13 00:22:00 INFO (AnyIO worker thread) [systembridgebackend.server.api] Authorized with API Key Header
2022-11-13 00:22:01 INFO (AnyIO worker thread) [systembridgebackend.server.api] API Key Header Result: True
2022-11-13 00:22:01 INFO (AnyIO worker thread) [systembridgebackend.server.api] API Key Query Result: False
2022-11-13 00:22:02 INFO (MainThread) [uvicorn.access] 192.168.1.100:52336 - "GET /api/data/system HTTP/1.1" 200
2022-11-13 00:22:02 INFO (MainThread) [uvicorn.error] ('192.168.1.100', 52336) - "WebSocket /api/websocket" [accepted]
2022-11-13 00:22:02 INFO (MainThread) [uvicorn.error] connection open
2022-11-13 00:22:02 INFO (MainThread) [systembridgebackend.server.websocket.WebSocketHandler] Received: REGISTER_DATA_LISTENER
2022-11-13 00:22:02 INFO (MainThread) [systembridgebackend.server.websocket.WebSocketHandler] Registering data listener: 30a421b0-2873-412c-a951-7aab1f76281d - ['battery', 'cpu', 'disk', 'display', 'gpu', 'memory', 'system']
2022-11-13 00:22:02 INFO (MainThread) [systembridgebackend.modules.listeners.Listeners] Added listener: 30a421b0-2873-412c-a951-7aab1f76281d
2022-11-13 00:22:02 INFO (MainThread) [systembridgebackend.modules.listeners.Listeners] Refresh data: ['battery', 'cpu', 'disk', 'display', 'gpu', 'memory', 'system']
2022-11-13 00:22:02 INFO (MainThread) [systembridgebackend.modules.listeners.Listeners] Refresh data by module: battery
2022-11-13 00:22:02 INFO (MainThread) [systembridgebackend.modules.listeners.Listeners] Data changed for module: battery
2022-11-13 00:22:02 INFO (MainThread) [systembridgebackend.modules.listeners.Listeners] Listener: 30a421b0-2873-412c-a951-7aab1f76281d - ['battery', 'cpu', 'disk', 'display', 'gpu', 'memory', 'system']
2022-11-13 00:22:02 INFO (MainThread) [systembridgebackend.modules.listeners.Listeners] Sending 'battery' data to listener: 30a421b0-2873-412c-a951-7aab1f76281d
2022-11-13 00:22:02 INFO (MainThread) [systembridgebackend.modules.listeners.Listeners] Refresh data by module: cpu
2022-11-13 00:22:02 INFO (MainThread) [systembridgebackend.modules.listeners.Listeners] Data changed for module: cpu
2022-11-13 00:22:02 INFO (MainThread) [systembridgebackend.modules.listeners.Listeners] Listener: 30a421b0-2873-412c-a951-7aab1f76281d - ['battery', 'cpu', 'disk', 'display', 'gpu', 'memory', 'system']
2022-11-13 00:22:02 INFO (MainThread) [systembridgebackend.modules.listeners.Listeners] Sending 'cpu' data to listener: 30a421b0-2873-412c-a951-7aab1f76281d
2022-11-13 00:22:02 INFO (MainThread) [systembridgebackend.modules.listeners.Listeners] Refresh data by module: disk
2022-11-13 00:22:02 INFO (MainThread) [systembridgebackend.modules.listeners.Listeners] Data changed for module: disk
2022-11-13 00:22:02 INFO (MainThread) [systembridgebackend.modules.listeners.Listeners] Listener: 30a421b0-2873-412c-a951-7aab1f76281d - ['battery', 'cpu', 'disk', 'display', 'gpu', 'memory', 'system']
2022-11-13 00:22:02 INFO (MainThread) [systembridgebackend.modules.listeners.Listeners] Sending 'disk' data to listener: 30a421b0-2873-412c-a951-7aab1f76281d
2022-11-13 00:22:02 INFO (MainThread) [systembridgebackend.modules.listeners.Listeners] Refresh data by module: display
2022-11-13 00:22:03 INFO (MainThread) [systembridgebackend.modules.listeners.Listeners] Data changed for module: display
2022-11-13 00:22:03 INFO (MainThread) [systembridgebackend.modules.listeners.Listeners] Listener: 30a421b0-2873-412c-a951-7aab1f76281d - ['battery', 'cpu', 'disk', 'display', 'gpu', 'memory', 'system']
2022-11-13 00:22:03 INFO (MainThread) [systembridgebackend.modules.listeners.Listeners] Sending 'display' data to listener: 30a421b0-2873-412c-a951-7aab1f76281d
2022-11-13 00:22:03 INFO (MainThread) [systembridgebackend.modules.listeners.Listeners] Refresh data by module: gpu
2022-11-13 00:22:04 INFO (MainThread) [systembridgebackend.modules.listeners.Listeners] Data changed for module: gpu
2022-11-13 00:22:04 INFO (MainThread) [systembridgebackend.modules.listeners.Listeners] Listener: 30a421b0-2873-412c-a951-7aab1f76281d - ['battery', 'cpu', 'disk', 'display', 'gpu', 'memory', 'system']
2022-11-13 00:22:04 INFO (MainThread) [systembridgebackend.modules.listeners.Listeners] Sending 'gpu' data to listener: 30a421b0-2873-412c-a951-7aab1f76281d
2022-11-13 00:22:04 INFO (MainThread) [systembridgebackend.modules.listeners.Listeners] Refresh data by module: memory
2022-11-13 00:22:04 INFO (MainThread) [systembridgebackend.modules.listeners.Listeners] Data changed for module: memory
2022-11-13 00:22:04 INFO (MainThread) [systembridgebackend.modules.listeners.Listeners] Listener: 30a421b0-2873-412c-a951-7aab1f76281d - ['battery', 'cpu', 'disk', 'display', 'gpu', 'memory', 'system']
2022-11-13 00:22:04 INFO (MainThread) [systembridgebackend.modules.listeners.Listeners] Sending 'memory' data to listener: 30a421b0-2873-412c-a951-7aab1f76281d
2022-11-13 00:22:04 INFO (MainThread) [systembridgebackend.modules.listeners.Listeners] Refresh data by module: system
2022-11-13 00:22:06 INFO (MainThread) [systembridgebackend.modules.listeners.Listeners] Data changed for module: system
2022-11-13 00:22:06 INFO (MainThread) [systembridgebackend.modules.listeners.Listeners] Listener: 30a421b0-2873-412c-a951-7aab1f76281d - ['battery', 'cpu', 'disk', 'display', 'gpu', 'memory', 'system']
2022-11-13 00:22:06 INFO (MainThread) [systembridgebackend.modules.listeners.Listeners] Sending 'system' data to listener: 30a421b0-2873-412c-a951-7aab1f76281d
2022-11-13 00:22:06 INFO (MainThread) [systembridgebackend.modules.listeners.Listeners] Finished refreshing data: ['battery', 'cpu', 'disk', 'display', 'gpu', 'memory', 'system']


Logs from HA
------------

2022-11-13 00:18:43.231 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/systembridgeconnector/websocket_client.py", line 492, in listen
    await self.listen_for_messages(callback=_callback_message)
  File "/usr/local/lib/python3.10/site-packages/systembridgeconnector/websocket_client.py", line 505, in listen_for_messages
    message = await self.receive_message()
  File "/usr/local/lib/python3.10/site-packages/systembridgeconnector/websocket_client.py", line 527, in receive_message
    raise ConnectionClosedException("Connection closed to server")
systembridgeconnector.exceptions.ConnectionClosedException: Connection closed to server
2022-11-13 00:22:03.021 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/system_bridge/coordinator.py", line 150, in _listen_for_data
    await self.websocket_client.listen(callback=self.async_handle_module)
  File "/usr/local/lib/python3.10/site-packages/systembridgeconnector/websocket_client.py", line 492, in listen
    await self.listen_for_messages(callback=_callback_message)
  File "/usr/local/lib/python3.10/site-packages/systembridgeconnector/websocket_client.py", line 507, in listen_for_messages
    await callback(message)
  File "/usr/local/lib/python3.10/site-packages/systembridgeconnector/websocket_client.py", line 480, in _callback_message
    model(**message[EVENT_DATA]),
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 2 validation errors for Display
displays
  field required (type=value_error.missing)
last_updated -> displays
  field required (type=value_error.missing)
```

**Comment by GGORG0** [comment]
+1. Same exact issue.

**Comment by aircooledbeemer** [comment]
+1 Seems I have the same issue...

**Comment by alexisspencer** [comment]
+1 here too
