### ISSUE TITLE
POST to /api/power/* results in Error 500

### ISSUE THREAD

**Issue by kjake** [timmo001/system-bridge#2134]
### Description

POST to API was previously working, but I updated to version 3.5.0 and now get Error 500 for all POST.

```zsh
➜  ~ curl -vvv --location --request POST 'http://192.168.1.7:9170/api/power/shutdown?apiKey=kEy'
*   Trying 192.168.1.7:9170...
* Connected to 192.168.1.7 (192.168.1.7) port 9170 (#0)
> POST /api/power/shutdown?apiKey=kEy HTTP/1.1
> Host: 192.168.1.7:9170
> User-Agent: curl/7.79.1
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 Internal Server Error
< date: Mon, 21 Nov 2022 22:04:00 GMT
< server: uvicorn
< content-length: 21
< content-type: text/plain; charset=utf-8
<
* Connection #0 to host 192.168.1.7 left intact
Internal Server Error%
```

### What Platform / OS are you running?

Windows

### What version are you running?

3.5.0

### Anything in the logs or a references that might be useful?

```txt
2022-11-21 17:04:00 INFO (MainThread) [uvicorn.access] 192.168.1.90:55130 - "POST /api/power/shutdown?apiKey=kEy HTTP/1.1" 500
2022-11-21 17:04:00 ERROR (MainThread) [uvicorn.error] Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\Kevin\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 419, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\Kevin\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\Kevin\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\Kevin\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\Kevin\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\Kevin\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\Kevin\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\Kevin\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\exceptions.py", line 75, in __call__
    raise exc
  File "C:\Users\Kevin\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\Kevin\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\Kevin\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\Kevin\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\Kevin\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "C:\Users\Kevin\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 65, in app
    response = await func(request)
  File "C:\Users\Kevin\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\routing.py", line 235, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\Kevin\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\routing.py", line 163, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "C:\Users\Kevin\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "C:\Users\Kevin\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\Kevin\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\Kevin\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\Kevin\AppData\Local\Programs\Python\Python310\lib\site-packages\systembridgebackend\server\api.py", line 468, in send_power_shutdown
    asyncio.get_running_loop().call_later(2, shutdown)
RuntimeError: no running event loop
```

**Comment by timmo001** [comment]
Can confirm this also occurs for other /api/power/* endpoints

**Comment by kjake** [comment]
Not sure how you want to handle this, but the same error exists for /api/notification, even in 3.5.1.

**Comment by timmo001** [comment]
> Not sure how you want to handle this, but the same error exists for /api/notification, even in 3.5.1.

Please open a new issue with the your logs
