### ISSUE TITLE
Python exception on startup under 3.6.1

### ISSUE THREAD

**Issue by subhuman-zz** [timmo001/system-bridge#2208]
### Description

Ubuntu 22.04.1 LTS
Kernel 5.15.0-56-generic
Running python 3.10.6

I followed the headless instructions, but have run into an issue:

using the command
python -m systembridgebackend

beings the startup sequence, but then coughs up complaining about the github releases file and exits gracefully.

### What Platform / OS are you running?

Linux

### What version are you running?

3.6.1

### Anything in the logs or a references that might be useful?

```txt
2022-12-26 15:14:46 INFO (Thread-2) [systembridgebackend.modules.listeners.Listeners] Refresh data by module: disk
2022-12-26 15:14:46 INFO (Thread-2) [systembridgebackend.modules.listeners.Listeners] Data changed for module: disk
2022-12-26 15:14:46 ERROR (Thread-2) [systembridgebackend.modules.system.System] Unexpected error getting data from GitHub: Unexpected exception for 'https://api.github.com/repos/timmo001/system-bridge/releases' with - cannot schedule new futures after interpreter shutdown
Traceback (most recent call last):
  File "/home/mmayer/.local/lib/python3.10/site-packages/aiogithubapi/client.py", line 138, in async_call_api
    result = await self._session.request(**request_arguments)
  File "/home/mmayer/.local/lib/python3.10/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/home/mmayer/.local/lib/python3.10/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/mmayer/.local/lib/python3.10/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/home/mmayer/.local/lib/python3.10/site-packages/aiohttp/connector.py", line 1152, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "/home/mmayer/.local/lib/python3.10/site-packages/aiohttp/connector.py", line 874, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "/home/mmayer/.local/lib/python3.10/site-packages/aiohttp/resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 860, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 818, in run_in_executor
    executor.submit(func, *args), loop=self)
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 169, in submit
    raise RuntimeError('cannot schedule new futures after '
RuntimeError: cannot schedule new futures after interpreter shutdown

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mmayer/.local/lib/python3.10/site-packages/systembridgebackend/modules/system/__init__.py", line 84, in version_latest
    releases = await github.repos.releases.list("timmo001/system-bridge")
  File "/home/mmayer/.local/lib/python3.10/site-packages/aiogithubapi/namespaces/releases.py", line 38, in list
    response = await self._client.async_call_api(
  File "/home/mmayer/.local/lib/python3.10/site-packages/aiogithubapi/client.py", line 152, in async_call_api
    raise GitHubException(
aiogithubapi.exceptions.GitHubException: Unexpected exception for 'https://api.github.com/repos/timmo001/system-bridge/releases' with - cannot schedule new futures after interpreter shutdown
2022-12-26 15:14:46 INFO (Thread-2) [systembridgebackend.modules.listeners.Listeners] Refresh data by module: system
2022-12-26 15:14:46 INFO (Thread-2) [systembridgebackend.modules.listeners.Listeners] Data changed for module: system
2022-12-26 15:14:46 INFO (Thread-2) [systembridgebackend.modules.update.Update] Finished updating data
2022-12-26 15:14:47 INFO (Thread-3) [systembridgebackend.modules.listeners.Listeners] Refresh data by module: cpu
2022-12-26 15:14:47 INFO (Thread-3) [systembridgebackend.modules.listeners.Listeners] Data changed for module: cpu
2022-12-26 15:14:47 INFO (Thread-3) [systembridgebackend.modules.listeners.Listeners] Refresh data by module: memory
2022-12-26 15:14:47 INFO (Thread-3) [systembridgebackend.modules.listeners.Listeners] Data changed for module: memory
2022-12-26 15:14:47 INFO (Thread-3) [systembridgebackend.modules.listeners.Listeners] Refresh data by module: network
2022-12-26 15:14:47 INFO (Thread-3) [systembridgebackend.modules.listeners.Listeners] Data changed for module: network
2022-12-26 15:14:47 INFO (Thread-3) [systembridgebackend.modules.update.Update] Finished updating frequent data
```

**Comment by subhuman-zz** [comment]
Note that this only shows up if you start without --no-gui.
