### ISSUE TITLE
Unable to run app on Ubuntu 22.04.3 LTS 

### ISSUE THREAD

**Issue by Tomlap123** [timmo001/system-bridge#2630]
### Description

Everything is installed as it should be but im still getting this errors in my logs: 
Im running Python 3.10.12

`tomlap@lapczuk:~$ python3 -m systembridgebackend
2023-08-09 00:19:21 INFO (MainThread) [systembridgebackend.Application] System Bridge 3.8.1: Startup
2023-08-09 00:19:21 INFO (MainThread) [systembridgebackend.Application] Autostart enabled: False
2023-08-09 00:19:22 INFO (MainThread) [systembridgebackend.server.Server] Setup API app
2023-08-09 00:19:22 INFO (MainThread) [systembridgebackend.server.Server] Setup API server
2023-08-09 00:19:22 INFO (MainThread) [systembridgebackend.server.Server] Server initialized
2023-08-09 00:19:22 INFO (MainThread) [systembridgebackend.server.Server] Start server
2023-08-09 00:19:22 INFO (MainThread) [uvicorn.error] Started server process [35264]
2023-08-09 00:19:22 INFO (MainThread) [uvicorn.error] Waiting for application startup.
2023-08-09 00:19:22 INFO (MainThread) [systembridgebackend.server.Server] Update data
2023-08-09 00:19:22 INFO (Thread-2) [systembridgebackend.modules.update.Update] Update data
2023-08-09 00:19:22 INFO (MainThread) [systembridgebackend.server.Server] Schedule next update in 2 minutes
2023-08-09 00:19:22 INFO (MainThread) [systembridgebackend.server.Server] Update frequent data
2023-08-09 00:19:22 INFO (Thread-3) [systembridgebackend.modules.update.Update] Update frequent data
2023-08-09 00:19:22 INFO (MainThread) [systembridgebackend.server.Server] Schedule next frequent update in 30 seconds
2023-08-09 00:19:22 INFO (MainThread) [systembridgebackend.server.Server] Update events data
2023-08-09 00:19:22 INFO (Thread-5 (_start_gui_sync)) [systembridgebackend.gui.GUI] Test WebSocket connection before starting GUI. Attempt #1
2023-08-09 00:19:22 INFO (MainThread) [systembridgebackend.server.Server] Register hotkeys
2023-08-09 00:19:22 INFO (MainThread) [systembridgebackend.server.Server] Found 0 hotkeys
2023-08-09 00:19:22 INFO (MainThread) [uvicorn.error] Application startup complete.
2023-08-09 00:19:22 INFO (MainThread) [uvicorn.error] Uvicorn running on http://0.0.0.0:9171 (Press CTRL+C to quit)
2023-08-09 00:19:22 INFO (Thread-5 (_start_gui_sync)) [systembridgeshared.websocket_client.WebSocketClient] Creating new aiohttp client session
2023-08-09 00:19:22 INFO (Thread-5 (_start_gui_sync)) [systembridgeshared.websocket_client.WebSocketClient] Connecting to WebSocket: ws://localhost:9171/api/websocket (aiohttp: 3.8.5)
2023-08-09 00:19:22 INFO (MainThread) [uvicorn.error] ('127.0.0.1', 44674) - "WebSocket /api/websocket" [accepted]
2023-08-09 00:19:22 INFO (MainThread) [uvicorn.error] connection open
2023-08-09 00:19:22 INFO (Thread-5 (_start_gui_sync)) [systembridgeshared.websocket_client.WebSocketClient] Connected to WebSocket
2023-08-09 00:19:22 INFO (Thread-5 (_start_gui_sync)) [systembridgeshared.websocket_client.WebSocketClient] Closing WebSocket connection
2023-08-09 00:19:22 INFO (Thread-5 (_start_gui_sync)) [systembridgebackend.gui.GUI] Connection test passed
2023-08-09 00:19:22 INFO (Thread-5 (_start_gui_sync)) [systembridgebackend.gui.GUI] Starting GUI: ['/usr/bin/python3', '-m', 'systembridgegui', 'main']
2023-08-09 00:19:22 INFO (MainThread) [systembridgebackend.server.websocket.WebSocketHandler] Connection closed: 1000
2023-08-09 00:19:22 INFO (MainThread) [systembridgebackend.server.websocket.WebSocketHandler] Unregistering data listener 0dac54b8-7bd0-4faf-93e6-d64ea1e62ffe
2023-08-09 00:19:22 INFO (Thread-5 (_start_gui_sync)) [systembridgebackend.gui.GUI] GUI started with PID: 35305
2023-08-09 00:19:22 INFO (MainThread) [systembridgebackend.modules.listeners.Listeners] Listener not found: 0dac54b8-7bd0-4faf-93e6-d64ea1e62ffe
2023-08-09 00:19:22 INFO (MainThread) [uvicorn.error] connection closed
2023-08-09 00:19:23 INFO (Thread-3) [systembridgebackend.modules.listeners.Listeners] Refresh data by module: sensors
2023-08-09 00:19:23 INFO (Thread-3) [systembridgebackend.modules.listeners.Listeners] Data changed for module: sensors
2023-08-09 00:19:23 INFO (Thread-3) [systembridgebackend.modules.listeners.Listeners] Refresh data by module: display
2023-08-09 00:19:23 INFO (Thread-3) [systembridgebackend.modules.listeners.Listeners] Data changed for module: display
2023-08-09 00:19:23 INFO (Thread-3) [systembridgebackend.modules.listeners.Listeners] Refresh data by module: gpu
2023-08-09 00:19:23 INFO (Thread-3) [systembridgebackend.modules.listeners.Listeners] Data changed for module: gpu
**2023-08-09 00:19:23 INFO (MainThread) [systembridgegui.Application] System Bridge GUI 3.8.1: Startup
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: wayland-egl, minimal, vkkhrdisplay, minimalegl, vnc, offscreen, wayland, eglfs, xcb, linuxfb.**

**2023-08-09 00:19:23 ERROR (Thread-5 (_start_gui_sync)) [systembridgebackend.gui.GUI] GUI exited with code: -6**
2023-08-09 00:19:23 INFO (Thread-5 (_start_gui_sync)) [systembridgebackend.gui.GUI] Test WebSocket connection before starting GUI. Attempt #2
2023-08-09 00:19:23 INFO (Thread-5 (_start_gui_sync)) [systembridgeshared.websocket_client.WebSocketClient] Creating new aiohttp client session
2023-08-09 00:19:23 INFO (Thread-5 (_start_gui_sync)) [systembridgeshared.websocket_client.WebSocketClient] Connecting to WebSocket: ws://localhost:9171/api/websocket (aiohttp: 3.8.5)
2023-08-09 00:19:23 INFO (MainThread) [uvicorn.error] ('127.0.0.1', 44684) - "WebSocket /api/websocket" [accepted]
2023-08-09 00:19:23 INFO (MainThread) [uvicorn.error] connection open
2023-08-09 00:19:23 INFO (Thread-5 (_start_gui_sync)) [systembridgeshared.websocket_client.WebSocketClient] Connected to WebSocket
2023-08-09 00:19:23 INFO (Thread-5 (_start_gui_sync)) [systembridgeshared.websocket_client.WebSocketClient] Closing WebSocket connection
2023-08-09 00:19:23 INFO (Thread-5 (_start_gui_sync)) [systembridgebackend.gui.GUI] Connection test passed
2023-08-09 00:19:23 INFO (MainThread) [systembridgebackend.server.websocket.WebSocketHandler] Connection closed: 1000
2023-08-09 00:19:23 INFO (Thread-5 (_start_gui_sync)) [systembridgebackend.gui.GUI] Starting GUI: ['/usr/bin/python3', '-m', 'systembridgegui', 'main']
2023-08-09 00:19:23 INFO (MainThread) [systembridgebackend.server.websocket.WebSocketHandler] Unregistering data listener de5b8c17-2e10-45be-a55d-a139525e0d85
2023-08-09 00:19:23 INFO (MainThread) [systembridgebackend.modules.listeners.Listeners] Listener not found: de5b8c17-2e10-45be-a55d-a139525e0d85
2023-08-09 00:19:23 INFO (Thread-5 (_start_gui_sync)) [systembridgebackend.gui.GUI] GUI started with PID: 35345
2023-08-09 00:19:23 INFO (MainThread) [uvicorn.error] connection closed
2023-08-09 00:19:24 INFO (MainThread) [systembridgegui.Application] System Bridge GUI 3.8.1: Startup
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: wayland-egl, minimal, vkkhrdisplay, minimalegl, vnc, offscreen, wayland, eglfs, xcb, linuxfb.

**2023-08-09 00:19:24 ERROR (Thread-5 (_start_gui_sync)) [systembridgebackend.gui.GUI] GUI exited with code: -6
2023-08-09 00:19:24 ERROR (Thread-5 (_start_gui_sync)) [systembridgebackend.gui.GUI] Failed to start GUI after 2 attempts**
2023-08-09 00:19:24 INFO (Thread-5 (_start_gui_sync)) [systembridgebackend.server.Server] Exiting application
2023-08-09 00:19:24 INFO (Thread-5 (_start_gui_sync)) [systembridgebackend.server.Server] Tasks cancelled
2023-08-09 00:19:24 INFO (Thread-5 (_start_gui_sync)) [systembridgebackend.gui.GUI] Stopping GUI: main
2023-08-09 00:19:24 INFO (Thread-5 (_start_gui_sync)) [systembridgebackend.gui.GUI] GUI stopped
2**023-08-09 00:19:24 INFO (Thread-5 (_start_gui_sync)) [systembridgebackend.server.Server] GUI stopped. Exiting Application
2023-08-09 00:19:27 ERROR (Thread-2) [systembridgebackend.modules.disk.Disk] PermissionError: [Errno 13] Permission denied: '/var/lib/docker/overlay2/f932b9ea458f9ba81c1d9b1dba6c6c57013bf146a28a2f6f708a4ee8b3fa58e1/merged'
2023-08-09 00:19:27 ERROR (Thread-2) [systembridgebackend.modules.disk.Disk] PermissionError: [Errno 13] Permission denied: '/var/lib/docker/overlay2/26f982530c9c1a9a1df0bb5d3d3bbdb95f514e444e41da4b2b8f133c0c8183ac/merged'
2023-08-09 00:19:27 ERROR (Thread-2) [systembridgebackend.modules.disk.Disk] PermissionError: [Errno 13] Permission denied: '/var/lib/docker/overlay2/cc98a9683f145792d8c5f9a4670d1075dc1fe12c097b8b21e658e96a08fcaf4f/merged'
2023-08-09 00:19:27 ERROR (Thread-2) [systembridgebackend.modules.disk.Disk] PermissionError: [Errno 13] Permission denied: '/var/lib/docker/overlay2/99dbb624cb1ce51134effd255bcdb13360e51b5757b2d6d5368c61b79b8ec175/merged'
2023-08-09 00:19:27 ERROR (Thread-2) [systembridgebackend.modules.disk.Disk] PermissionError: [Errno 13] Permission denied: '/var/lib/docker/overlay2/198cccd7e94ffb44fd1d66131b51cb44edaec7996ecc99710c98e4b0e26b8c7e/merged'
2023-08-09 00:19:27 ERROR (Thread-2) [systembridgebackend.modules.disk.Disk] PermissionError: [Errno 13] Permission denied: '/var/lib/docker/overlay2/0568541adf7b75f1c2c1463991cffbf3a5ce50fcf96f0f5fdcf62dbf366ab5de/merged'
2023-08-09 00:19:27 ERROR (Thread-2) [systembridgebackend.modules.disk.Disk] PermissionError: [Errno 13] Permission denied: '/var/lib/docker/overlay2/9eccbb1d39133048ca7a486f72fe438cc0382972fc9c5f66e12f422314414e51/merged'
2023-08-09 00:19:27 ERROR (Thread-2) [systembridgebackend.modules.disk.Disk] PermissionError: [Errno 13] Permission denied: '/run/docker/netns/default'
2023-08-09 00:19:27 ERROR (Thread-2) [systembridgebackend.modules.disk.Disk] PermissionError: [Errno 13] Permission denied: '/var/lib/docker/overlay2/51323ec14757e6319ab40613dff08eb26aae813562f5de7d173bd8238b1d2d82/merged'
2023-08-09 00:19:27 ERROR (Thread-2) [systembridgebackend.modules.disk.Disk] PermissionError: [Errno 13] Permission denied: '/var/lib/docker/overlay2/50ccd78a19df42d8c84f3db63b0946066e471bb0068d9304c887940e918ccde4/merged'
2023-08-09 00:19:27 ERROR (Thread-2) [systembridgebackend.modules.disk.Disk] PermissionError: [Errno 13] Permission denied: '/var/lib/docker/overlay2/24c2d3b50eec41088c93f56235f6d2001d0160d8736c9fbda0cd721acfd3a135/merged'
2023-08-09 00:19:27 ERROR (Thread-2) [systembridgebackend.modules.disk.Disk] PermissionError: [Errno 13] Permission denied: '/var/lib/docker/overlay2/94bcdfd352d1279919f48f0d6c9a868ab7a11e764aa55b0a41c4078e852304d5/merged'
2023-08-09 00:19:27 ERROR (Thread-2) [systembridgebackend.modules.disk.Disk] PermissionError: [Errno 13] Permission denied: '/var/lib/docker/overlay2/78c4a70bbc963d30403b2354f2529cf6cd3f38b88232741f6b05306782c6a7e5/merged'
2023-08-09 00:19:27 ERROR (Thread-2) [systembridgebackend.modules.disk.Disk] PermissionError: [Errno 13] Permission denied: '/run/docker/netns/5f6a4c7aa9a5'
2023-08-09 00:19:27 ERROR (Thread-2) [systembridgebackend.modules.disk.Disk] PermissionError: [Errno 13] Permission denied: '/run/docker/netns/a7327997da79'
2023-08-09 00:19:27 ERROR (Thread-2) [systembridgebackend.modules.disk.Disk] PermissionError: [Errno 13] Permission denied: '/run/docker/netns/e085a008a142'
2023-08-09 00:19:27 ERROR (Thread-2) [systembridgebackend.modules.disk.Disk] PermissionError: [Errno 13] Permission denied: '/run/docker/netns/7ad56c79a5b0'
2023-08-09 00:19:27 ERROR (Thread-2) [systembridgebackend.modules.disk.Disk] PermissionError: [Errno 13] Permission denied: '/run/docker/netns/c650760ec708'
2023-08-09 00:19:27 ERROR (Thread-2) [systembridgebackend.modules.disk.Disk] PermissionError: [Errno 13] Permission denied: '/run/docker/netns/fddc79ce046f'
2023-08-09 00:19:27 ERROR (Thread-2) [systembridgebackend.modules.disk.Disk] PermissionError: [Errno 13] Permission denied: '/run/docker/netns/ccf3b014e2e7'
2023-08-09 00:19:27 ERROR (Thread-2) [systembridgebackend.modules.disk.Disk] PermissionError: [Errno 13] Permission denied: '/run/docker/netns/5e75ba35a764'
2023-08-09 00:19:27 ERROR (Thread-2) [systembridgebackend.modules.disk.Disk] PermissionError: [Errno 13] Permission denied: '/var/lib/docker/overlay2/ee6898c4c2b23cecb80360685e5e70a0140e3282a7b9692563a44ea91e3d8526/merged'
2023-08-09 00:19:27 ERROR (Thread-2) [systembridgebackend.modules.disk.Disk] PermissionError: [Errno 13] Permission denied: '/run/docker/netns/c25c90661f0c'**
2023-08-09 00:19:27 INFO (Thread-2) [systembridgebackend.modules.system.System] Get latest version from GitHub
2023-08-09 00:19:27 INFO (Thread-2) [systembridgebackend.modules.listeners.Listeners] Refresh data by module: battery
2023-08-09 00:19:27 INFO (Thread-2) [systembridgebackend.modules.listeners.Listeners] Data changed for module: battery
2023-08-09 00:19:27 INFO (Thread-2) [systembridgebackend.modules.listeners.Listeners] Refresh data by module: disk
2023-08-09 00:19:27 INFO (Thread-2) [systembridgebackend.modules.listeners.Listeners] Data changed for module: disk
**2023-08-09 00:19:27 ERROR (Thread-2) [systembridgebackend.modules.system.System] Unexpected error getting data from GitHub: Unexpected exception for 'https://api.github.com/repos/timmo001/system-bridge/releases' with - cannot schedule new futures after interpreter shutdown**
Traceback (most recent call last):
  File "/home/tomlap/.local/lib/python3.10/site-packages/aiogithubapi/client.py", line 138, in async_call_api
    result = await self._session.request(**request_arguments)
  File "/home/tomlap/.local/lib/python3.10/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/home/tomlap/.local/lib/python3.10/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/tomlap/.local/lib/python3.10/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/home/tomlap/.local/lib/python3.10/site-packages/aiohttp/connector.py", line 1155, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "/home/tomlap/.local/lib/python3.10/site-packages/aiohttp/connector.py", line 874, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "/home/tomlap/.local/lib/python3.10/site-packages/aiohttp/resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 863, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 821, in run_in_executor
    executor.submit(func, *args), loop=self)
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 169, in submit
    raise RuntimeError('cannot schedule new futures after '
RuntimeError: cannot schedule new futures after interpreter shutdown

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tomlap/.local/lib/python3.10/site-packages/systembridgebackend/modules/system/__init__.py", line 84, in version_latest
    releases = await github.repos.releases.list("timmo001/system-bridge")
  File "/home/tomlap/.local/lib/python3.10/site-packages/aiogithubapi/namespaces/releases.py", line 38, in list
    response = await self._client.async_call_api(
  File "/home/tomlap/.local/lib/python3.10/site-packages/aiogithubapi/client.py", line 152, in async_call_api
    raise GitHubException(
aiogithubapi.exceptions.GitHubException: Unexpected exception for 'https://api.github.com/repos/timmo001/system-bridge/releases' with - cannot schedule new futures after interpreter shutdown
2023-08-09 00:19:27 INFO (Thread-2) [systembridgebackend.modules.listeners.Listeners] Refresh data by module: system
2023-08-09 00:19:27 INFO (Thread-2) [systembridgebackend.modules.listeners.Listeners] Data changed for module: system
2023-08-09 00:19:27 INFO (Thread-2) [systembridgebackend.modules.update.Update] Finished updating data
2023-08-09 00:19:29 INFO (Thread-3) [systembridgebackend.modules.listeners.Listeners] Refresh data by module: cpu
2023-08-09 00:19:29 INFO (Thread-3) [systembridgebackend.modules.listeners.Listeners] Data changed for module: cpu
2023-08-09 00:19:29 INFO (Thread-3) [systembridgebackend.modules.listeners.Listeners] Refresh data by module: memory
2023-08-09 00:19:29 INFO (Thread-3) [systembridgebackend.modules.listeners.Listeners] Data changed for module: memory
2023-08-09 00:19:29 INFO (Thread-3) [systembridgebackend.modules.listeners.Listeners] Refresh data by module: network
2023-08-09 00:19:29 INFO (Thread-3) [systembridgebackend.modules.listeners.Listeners] Data changed for module: network
2023-08-09 00:19:29 INFO (Thread-3) [systembridgebackend.modules.update.Update] Finished updating frequent data`

### What Platform / OS are you running?

Linux

### What version are you running?

Ubuntu 22.04.3 LTS

**Comment by Tomlap123** [comment]
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: wayland-egl, minimal, vkkhrdisplay, minimalegl, vnc, offscreen, wayland, eglfs, xcb, linuxfb.

2023-08-09 00:19:23 ERROR (Thread-5 (_start_gui_sync)) [systembridgebackend.gui.GUI] GUI exited with code: -6

**Comment by ondras12345** [comment]
Still a problem

**Comment by Kisty** [comment]
Managed to solve this. Try installing `libxcb-cursor0`. Also had to install `xclip` to copy API key to clipboard on Debian 12 bookworm

**Comment by timmo001** [comment]
Let me know if this solved your problem and reopen if not. Also make sure to use the latest version and run python 3.12+ or use the binary version.

Thanks!
