### ISSUE TITLE
Run as a window service

### ISSUE THREAD

**Issue by DeFlanko** [timmo001/system-bridge#2700]
### Description

I have a remote box that i RDP into, i would like System bridge to run as a service so it can run without me being RDP'd into it -- ideally so i can monitor it though Home assistant as intended. 

i've tried:
```cmd
sc.exe create "System Bridge Service (no gui)" binPath= "C:\systembridge\systembridge.exe --no-gui"
```
and then assigning a local user account to the service but fails to stay running.

i've also tried 
```cmd
sc.exe create "System Bridge Service" binPath= "C:\systembridge\systembridge.exe"
```
Which runs but Home assistant never can connect to it

-----

i've even tried the method described in the notes: https://system-bridge.timmo.dev/docs/running
```python
C:\systembridge>python -m pip install --upgrade systembridgecli
Requirement already satisfied: systembridgecli in c:\users\defla\appdata\local\programs\python\python311\lib\site-packages (3.8.2)
Requirement already satisfied: incremental==22.10.0 in c:\users\defla\appdata\local\programs\python\python311\lib\site-packages (from systembridgecli) (22.10.0)
Requirement already satisfied: pyinstaller==5.13.0 in c:\users\defla\appdata\local\programs\python\python311\lib\site-packages (from systembridgecli) (5.13.0)
Requirement already satisfied: shellingham==1.5.0.post1 in c:\users\defla\appdata\local\programs\python\python311\lib\site-packages (from systembridgecli) (1.5.0.post1)
Requirement already satisfied: tabulate==0.9.0 in c:\users\defla\appdata\local\programs\python\python311\lib\site-packages (from systembridgecli) (0.9.0)
Requirement already satisfied: typer==0.9.0 in c:\users\defla\appdata\local\programs\python\python311\lib\site-packages (from systembridgecli) (0.9.0)
Requirement already satisfied: setuptools>=42.0.0 in c:\users\defla\appdata\local\programs\python\python311\lib\site-packages (from pyinstaller==5.13.0->systembridgecli) (65.5.0)
Requirement already satisfied: altgraph in c:\users\defla\appdata\local\programs\python\python311\lib\site-packages (from pyinstaller==5.13.0->systembridgecli) (0.17.3)
Requirement already satisfied: pyinstaller-hooks-contrib>=2021.4 in c:\users\defla\appdata\local\programs\python\python311\lib\site-packages (from pyinstaller==5.13.0->systembridgecli) (2023.8)
Requirement already satisfied: pefile>=2022.5.30 in c:\users\defla\appdata\local\programs\python\python311\lib\site-packages (from pyinstaller==5.13.0->systembridgecli) (2023.2.7)
Requirement already satisfied: pywin32-ctypes>=0.2.1 in c:\users\defla\appdata\local\programs\python\python311\lib\site-packages (from pyinstaller==5.13.0->systembridgecli) (0.2.2)
Requirement already satisfied: click<9.0.0,>=7.1.1 in c:\users\defla\appdata\local\programs\python\python311\lib\site-packages (from typer==0.9.0->systembridgecli) (8.1.7)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\users\defla\appdata\local\programs\python\python311\lib\site-packages (from typer==0.9.0->systembridgecli) (4.7.1)
Requirement already satisfied: colorama in c:\users\defla\appdata\local\programs\python\python311\lib\site-packages (from click<9.0.0,>=7.1.1->typer==0.9.0->systembridgecli) (0.4.6)

C:\systembridge>python -m systembridgecli api-key
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\systembridge\systembridgecli\__main__.py", line 11, in <module>
    from systembridgeshared.common import get_user_data_directory
  File "C:\systembridge\systembridgeshared\common.py", line 10, in <module>
    from appdirs import AppDirs
ModuleNotFoundError: No module named 'appdirs'
```

 I have installed the app outside of the default folder location -- is this why that step is failing?

**Comment by DeFlanko** [comment]
[Start System Bridge.zip](https://github.com/timmo001/system-bridge/files/12566600/Start.System.Bridge.zip)
Created a Task Scheduler in hopes of resolving any issue -- both the gui or no-gui option running as the service account but home assistant still fails to connect. 

(I created a separate Service account on my machine "SYS_BRDG") 

if you plan on going this route be sure to follow these steps:
On the local server use Local Security Policy manager:

1. Click START and type `secpol.msc` then press Enter
2. Expand Security Settings > Local Policies > User Rights Assignment node
3. Double click `Log on as a batch job`
4. Click the Add User or Group button and add your service account user
5. Click OK, Done

**Comment by DeFlanko** [comment]
Well ok its a hell of a work around but i think i got it... 

So i had to grant my SYS_BRDG account the ability to RDP back to the host, once i did that i then relogged into my Host box as SYS_BRDG, re-ran the Systembridge.exe gui version, clicked on help and copied the API key -- **_which to my surprise was a DIFFERENT API KEY..._** 

saved that NEW API key back into Home Assistant and now the app is running as a Windows Task, without me logged in, and visible in Home Assistant

![image](https://github.com/timmo001/system-bridge/assets/5233969/e3ce2d02-25a1-4c24-afb6-83e5269fc075)
