### ISSUE TITLE
Cannot run systembridge at all

### ISSUE THREAD

**Issue by TomerSchDev** [timmo001/system-bridge#2727]
### Description

After installing the deb version (3.8.2) i tried calling systembridge from the cli,

I can only run it as a sudo user, and it crush when i try to run it with gui

### What Platform / OS are you running?

Linux

### What version are you running?

3.8.2

### Anything in the logs or a references that might be useful?

```txt
Exception in thread Thread-5 (_start_gui_sync):
Traceback (most recent call last):
  File "threading.py", line 1038, in _bootstrap_inner
  File "threading.py", line 975, in run
  File "systembridgebackend/gui.py", line 143, in _start_gui_sync
  File "asyncio/runners.py", line 190, in run
  File "asyncio/runners.py", line 118, in run
  File "asyncio/base_events.py", line 653, in run_until_complete
  File "systembridgebackend/gui.py", line 73, in _start
  File "systembridgeshared/websocket_client.py", line 149, in connect
  File "aiohttp/client.py", line 779, in _ws_connect
  File "aiohttp/client.py", line 536, in _request
  File "aiohttp/connector.py", line 540, in connect
  File "aiohttp/connector.py", line 901, in _create_connection
  File "aiohttp/connector.py", line 1155, in _create_direct_connection
  File "aiohttp/connector.py", line 874, in _resolve_host
  File "aiohttp/resolver.py", line 33, in resolve
  File "asyncio/base_events.py", line 867, in getaddrinfo
  File "asyncio/base_events.py", line 829, in run_in_executor
  File "concurrent/futures/thread.py", line 169, in submit
RuntimeError: cannot schedule new futures after interpreter shutdown
2023-09-21 19:07:15 ERROR (Thread-2) [asyncio] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f458df696d0>
2023-09-21 19:07:16 INFO (Thread-3) [systembridgebackend.modules.listeners.Listeners] Refresh data by module: sensors
2023-09-21 19:07:16 INFO (Thread-3) [systembridgebackend.modules.listeners.Listeners] Data changed for module: sensors
2023-09-21 19:07:16 INFO (Thread-3) [systembridgebackend.modules.listeners.Listeners] Refresh data by module: display
2023-09-21 19:07:16 INFO (Thread-3) [systembridgebackend.modules.listeners.Listeners] Data changed for module: display
2023-09-21 19:07:16 INFO (Thread-3) [systembridgebackend.modules.listeners.Listeners] Refresh data by module: gpu
2023-09-21 19:07:16 INFO (Thread-3) [systembridgebackend.modules.listeners.Listeners] Data changed for module: gpu
2023-09-21 19:07:25 INFO (Thread-3) [systembridgebackend.modules.listeners.Listeners] Refresh data by module: cpu
2023-09-21 19:07:25 INFO (Thread-3) [systembridgebackend.modules.listeners.Listeners] Data changed for module: cpu
2023-09-21 19:07:25 INFO (Thread-3) [systembridgebackend.modules.listeners.Listeners] Refresh data by module: memory
2023-09-21 19:07:25 INFO (Thread-3) [systembridgebackend.modules.listeners.Listeners] Data changed for module: memory
2023-09-21 19:07:25 INFO (Thread-3) [systembridgebackend.modules.listeners.Listeners] Refresh data by module: network
2023-09-21 19:07:25 INFO (Thread-3) [systembridgebackend.modules.listeners.Listeners] Data changed for module: network
2023-09-21 19:07:25 INFO (Thread-3) [systembridgebackend.modules.update.Update] Finished updating frequent data
2023-09-21 19:07:29 INFO (Thread-2) [systembridgebackend.modules.system.System] Get latest version from GitHub
2023-09-21 19:07:29 INFO (Thread-2) [systembridgebackend.modules.listeners.Listeners] Refresh data by module: battery
2023-09-21 19:07:29 INFO (Thread-2) [systembridgebackend.modules.listeners.Listeners] Data changed for module: battery
2023-09-21 19:07:29 INFO (Thread-2) [systembridgebackend.modules.listeners.Listeners] Refresh data by module: disk
2023-09-21 19:07:29 INFO (Thread-2) [systembridgebackend.modules.listeners.Listeners] Data changed for module: disk
2023-09-21 19:07:29 ERROR (Thread-2) [systembridgebackend.modules.system.System] Unexpected error getting data from GitHub: Unexpected exception for 'https://api.github.com/repos/timmo001/system-bridge/releases' with - cannot schedule new futures after interpreter shutdown
Traceback (most recent call last):
  File "aiogithubapi/client.py", line 138, in async_call_api
  File "aiohttp/client.py", line 536, in _request
  File "aiohttp/connector.py", line 540, in connect
  File "aiohttp/connector.py", line 901, in _create_connection
  File "aiohttp/connector.py", line 1155, in _create_direct_connection
  File "aiohttp/connector.py", line 874, in _resolve_host
  File "aiohttp/resolver.py", line 33, in resolve
  File "asyncio/base_events.py", line 867, in getaddrinfo
  File "asyncio/base_events.py", line 829, in run_in_executor
  File "concurrent/futures/thread.py", line 169, in submit
RuntimeError: cannot schedule new futures after interpreter shutdown

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "systembridgebackend/modules/system/__init__.py", line 84, in version_latest
    releases = await github.repos.releases.list("timmo001/system-bridge")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "aiogithubapi/namespaces/releases.py", line 38, in list
  File "aiogithubapi/client.py", line 152, in async_call_api
aiogithubapi.exceptions.GitHubException: Unexpected exception for 'https://api.github.com/repos/timmo001/system-bridge/releases' with - cannot schedule new futures after interpreter shutdown
```

**Comment by timmo001** [comment]
This should have been resolved in the later versions of the app. Please reopen with updated log output if still running into this issue
