### ISSUE TITLE
battery: ValueError: could not convert string to float: 'False'

### ISSUE THREAD

**Issue by bwduncan** [timmo001/system-bridge#2871]
### Description

```
(venv) :) bduncan@w7700:~$ python -m systembridgecli data battery
Traceback (most recent call last):

  File "<frozen runpy>", line 198, in _run_module_as_main

  File "<frozen runpy>", line 88, in _run_code

  File "/home/bduncan/venv/lib/python3.11/site-packages/systembridgecli/__main__.py", line 161, in <module>
    app()

  File "/home/bduncan/venv/lib/python3.11/site-packages/systembridgecli/__main__.py", line 50, in data
    table_data = tabulate(output, headers="keys", tablefmt="psql")
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/bduncan/venv/lib/python3.11/site-packages/tabulate/__init__.py", line 2153, in tabulate
    cols = [
           ^

  File "/home/bduncan/venv/lib/python3.11/site-packages/tabulate/__init__.py", line 2154, in <listcomp>
    [_format(v, ct, fl_fmt, int_fmt, miss_v, has_invisible) for v in c]

  File "/home/bduncan/venv/lib/python3.11/site-packages/tabulate/__init__.py", line 2154, in <listcomp>
    [_format(v, ct, fl_fmt, int_fmt, miss_v, has_invisible) for v in c]
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/bduncan/venv/lib/python3.11/site-packages/tabulate/__init__.py", line 1232, in _format
    return format(float(val), floatfmt)
                  ^^^^^^^^^^

ValueError: could not convert string to float: 'False'

(venv) :( 1 bduncan@w7700:~$ 
```

```
(venv) :( 1 bduncan@w7700:~$ pip freeze | grep system
systembridge==2.3.1
systembridgebackend==3.11.2
systembridgecli==3.9.14
systembridgeconnector==3.10.1
systembridgefrontend==3.11.1
systembridgegui==3.9.7
systembridgemodels==3.10.5
systembridgeshared==3.10.6
```

(it looks like installing systembridgeconnector has downgraded systembridgemodels, but the bug was there with the newer version, too)

```python
In [1]: import psutil

In [2]: psutil.sensors_battery()
Out[2]: sbattery(percent=99.18295885614239, secsleft=<BatteryTime.POWER_TIME_UNLIMITED: -2>, power_plugged=True)
```

### What Platform / OS are you running?

Linux

### What version are you running?

3.11.2

**Comment by timmo001** [comment]
Replaced in https://github.com/timmo001/system-bridge-backend/commit/4a7d52dc12eff31cf21195c417b7760c84e96a92
