### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

### ISSUE THREAD

**Issue by pelmered** [timmo001/system-bridge#2875]
### Description

Looks like it is the same problem as in #1831, but I have the latest version. 

```
python3 -m systembridgebackend --no-gui
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.9/runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/peter/.local/lib/python3.9/site-packages/systembridgebackend/__init__.py", line 10, in <module>
    from systembridgeshared.database import Database
  File "/home/peter/.local/lib/python3.9/site-packages/systembridgeshared/database.py", line 11, in <module>
    from systembridgemodels.const import (
  File "/home/peter/.local/lib/python3.9/site-packages/systembridgemodels/const.py", line 2, in <module>
    from .battery import Battery
  File "/home/peter/.local/lib/python3.9/site-packages/systembridgemodels/battery.py", line 9, in <module>
    class LastUpdated(BaseModel):
  File "/home/peter/.local/lib/python3.9/site-packages/pydantic/main.py", line 178, in __new__
    annotations = resolve_annotations(namespace.get('__annotations__', {}), namespace.get('__module__', None))
  File "/home/peter/.local/lib/python3.9/site-packages/pydantic/typing.py", line 400, in resolve_annotations
    value = _eval_type(value, base_globals, None)
  File "/usr/lib/python3.9/typing.py", line 283, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "/usr/lib/python3.9/typing.py", line 539, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```

Info about installed packages:
```
python3 -m pip show systembridgeshared systembridgebackend systembridgecli
Name: systembridgeshared
Version: 3.10.6
Summary: System Bridge Shared
Home-page: https://github.com/timmo001/system-bridge-shared
Author: Aidan Timson (Timmo)
Author-email: aidan@timmo.dev
License: MIT
Location: /home/peter/.local/lib/python3.9/site-packages
Requires: aiohttp, appdirs, colorlog, cryptography, incremental, pandas, sqlmodel, systembridgemodels
Required-by: systembridgebackend, systembridgecli
---
Name: systembridgebackend
Version: 3.11.2
Summary: System Bridge Backend
Home-page: https://github.com/timmo001/system-bridge-backend
Author: Aidan Timson (Timmo)
Author-email: aidan@timmo.dev
License: MIT
Location: /home/peter/.local/lib/python3.9/site-packages
Requires: aiofiles, fastapi, incremental, keyboard, mutagen, plyer, psutil, python-multipart, screeninfo, systembridgemodels, systembridgeshared, typer, uvicorn, zeroconf
Required-by:
---
Name: systembridgecli
Version: 3.9.14
Summary: System Bridge CLI
Home-page: https://github.com/timmo001/system-bridge-cli
Author: Aidan Timson (Timmo)
Author-email: aidan@timmo.dev
License: MIT
Location: /home/peter/.local/lib/python3.9/site-packages
Requires: incremental, shellingham, systembridgeshared, tabulate, typer
Required-by:
```

I'm running this on a Raspberry Pi 3B so it is a 32-bit system. There was only pre built packages for 64-bit systems so I had to install using Python / PIP. It looks like the versions don't match, but that is what I got with `python3 -m pip install --upgrade systembridgeshared systembridgebackend systembridgecli`. Could that be a problem? 

### What Platform / OS are you running?

Linux

### What version are you running?

3.11.2

**Comment by timmo001** [comment]
Python 3.9 is not supported 

https://system-bridge.timmo.dev/docs/install-python
