### ISSUE TITLE
Error on new install Debian 10 & 11

### ISSUE THREAD

**Issue by MrToast72** [timmo001/system-bridge#2882]
### Description

I cannot use Systembridge on a few different machines, all running either Debian 10 (for my home servers) or Debian 11 (on my laptop and desktop).

For my machines running Debian 10 I get this error trying to run systembridge from the terminal:

```
[656326] Error loading Python lib '/usr/local/share/systembridge/_internal/libpython3.12.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by /usr/local/share/systembridge/_internal/libpython3.12.so.1.0)
```

I tried updating Python to the latest version. My current version while trying to run a fresh install is:

```
 ➜  ~ python --version
Python 3.12.1
```

as for my debian 11 machines I encounter this error:

```
➜  ~ systembridge
2023-12-30 08:26:14 INFO (MainThread) [systembridgebackend.server.api] Serving frontend from: /usr/local/share/systembridge/_internal/systembridgefrontend/out
2023-12-30 08:26:14 INFO (MainThread) [systembridgebackend.Application] System Bridge 3.11.2: Startup
2023-12-30 08:26:14 INFO (MainThread) [systembridgebackend.Application] Your api-key is: de8dd7a8-9ae9-4c9b-95b5-84ecbff753c5
2023-12-30 08:26:14 INFO (MainThread) [systembridgebackend.Application] Autostart enabled: False
lshw not found.2023-12-30 08:26:14 CRITICAL (MainThread) [root] Unhandled error in application
Traceback (most recent call last):
  File "systembridge.py", line 51, in application
  File "systembridgebackend/__init__.py", line 57, in __init__
    self._server = Server(
                   ^^^^^^^
  File "systembridgebackend/server/__init__.py", line 71, in __init__
    self._mdns_advertisement.advertise_server()
  File "systembridgebackend/server/mdns.py", line 32, in advertise_server
    system_id = system.uuid()
                ^^^^^^^^^^^^^
  File "systembridgebackend/modules/system.py", line 209, in uuid
    return uniqueid.id or self.mac_address()
           ^^^^^^^^^^^
  File "plyer/utils.py", line 117, in __getattribute__
    result = getattr(object.__getattribute__(self, '_obj'), name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "plyer/facades/uniqueid.py", line 42, in id
    return self.get_uid()
           ^^^^^^^^^^^^^^
  File "plyer/facades/uniqueid.py", line 49, in get_uid
    return self._get_uid()
           ^^^^^^^^^^^^^^^
  File "plyer/facades/uniqueid.py", line 54, in _get_uid
    raise NotImplementedError()
NotImplementedError
```

python version for both machines running debian 11:

```
➜  ~ python --version
Python 3.11.2
```

I'm not sure where to go from here in both cases. I tried installing it manually using Python via the terminal for my Debian 10 machines, and that gave me the same error above. I tried looking around at other issues in the discussion and couldn't find anything more than install the latest Python; if I missed something, however, I do apologize in advance!

### What Platform / OS are you running?

Linux

### What version are you running?

3.11.1

**Comment by timmo001** [comment]
Fixed in #2884
