### ISSUE TITLE
openSUSE Tumbleweed Installation

### ISSUE THREAD

**Issue by BeardedTek** [timmo001/system-bridge#2883]
### Description

Will not cleanly install on openSUSE Tumbleweed

### Installing via RPM gets the following errors:
```
sudo zypper in ./systembridge-3.11.2.x86_64.rpm
Loading repository data...
Reading installed packages...
Resolving package dependencies...

Problem: nothing provides 'avahi-compat-libdns_sd-devel' needed by the to be installed systembridge-3.11.2-1.x86_64
 Solution 1: do not install systembridge-3.11.2-1.x86_64
 Solution 2: break systembridge-3.11.2-1.x86_64 by ignoring some of its dependencies

Choose from above solutions by number or cancel [1/2/c/d/?] (c):
```
### Forcing it will allow installation:
```
sudo zypper in ./systembridge-3.11.2.x86_64.rpm
Loading repository data...
Reading installed packages...
Resolving package dependencies...

Problem: nothing provides 'avahi-compat-libdns_sd-devel' needed by the to be installed systembridge-3.11.2-1.x86_64
 Solution 1: do not install systembridge-3.11.2-1.x86_64
 Solution 2: break systembridge-3.11.2-1.x86_64 by ignoring some of its dependencies

Choose from above solutions by number or cancel [1/2/c/d/?] (c): 2
Resolving dependencies...
Resolving package dependencies...

The following NEW package is going to be installed:
  systembridge

1 new package to install.
Overall download size: 248.6 MiB. Already cached: 0 B. After the operation, additional 612.5 MiB will be used.
Continue? [y/n/v/...? shows all options] (y):
Retrieving: systembridge-3.11.2-1.x86_64 (Plain RPM files cache)                                                                                                                             (1/1), 248.6 MiB
systembridge-3.11.2.x86_64.rpm:
    Package header is not signed!

systembridge-3.11.2-1.x86_64 (Plain RPM files cache): Signature verification failed [6-File is unsigned]
Abort, retry, ignore? [a/r/i] (a): i

Checking for file conflicts: ..............................................................................................................................................................................[done]
(1/1) Installing: systembridge-3.11.2-1.x86_64 ............................................................................................................................................................[done]
Running post-transaction scripts ..........................................................................................................................................................................[done]
```

### When Run Headless it functions, but this error repeats each time it grabs data:

```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "aiohttp/connector.py", line 988, in _wrap_create_connection
  File "asyncio/base_events.py", line 1126, in create_connection
  File "asyncio/base_events.py", line 1159, in _create_connection_transport
  File "asyncio/sslproto.py", line 575, in _on_handshake_complete
  File "asyncio/sslproto.py", line 557, in _do_handshake
  File "ssl.py", line 917, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "threading.py", line 1052, in _bootstrap_inner
  File "systembridgebackend/data.py", line 29, in run
  File "asyncio/runners.py", line 194, in run
  File "asyncio/runners.py", line 118, in run
  File "asyncio/base_events.py", line 664, in run_until_complete
  File "systembridgebackend/modules/__init__.py", line 74, in update_data
  File "systembridgebackend/modules/__init__.py", line 66, in _update
  File "systembridgebackend/modules/system.py", line 449, in update_all_data
  File "systembridgebackend/modules/system.py", line 432, in update_version_latest
  File "systembridgebackend/modules/system.py", line 220, in version_latest
  File "aiohttp/client.py", line 1187, in __aenter__
  File "aiohttp/client.py", line 574, in _request
  File "aiohttp/connector.py", line 540, in connect
  File "aiohttp/connector.py", line 907, in _create_connection
  File "aiohttp/connector.py", line 1231, in _create_direct_connection
  File "aiohttp/connector.py", line 1200, in _create_direct_connection
  File "aiohttp/connector.py", line 990, in _wrap_create_connection
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host api.github.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)')]
```

### What Platform / OS are you running?

Linux

### What version are you running?

3.11.2

### Additional information

Please feel free to reach out for testing, more information, etc.

**Comment by timmo001** [comment]
Fixed in #2884
