### ISSUE TITLE
Exit via tray and Ctrl+C doesnt exit (Package/Executable)

### ISSUE THREAD

**Issue by timmo001** [timmo001/system-bridge#2885]
### Description

Works when running backend in python, not via package

### What Platform / OS are you running?

Windows/Linux

### What version are you running?

4.0.0 (DEV)

### Anything in the logs or a references that might be useful?

```
^C2024-01-07 16:39:58 INFO (MainThread) [systembridgebackend.server.Server] Exiting application
2024-01-07 16:40:00 INFO (MainThread) [systembridgebackend.handlers.threads.data.DataUpdateThread] Stopped update thread
2024-01-07 16:40:00 INFO (MainThread) [systembridgebackend.handlers.threads.data.DataUpdateThread] Stopping thread
2024-01-07 16:40:00 INFO (MainThread) [systembridgebackend.handlers.threads.media.MediaUpdateThread] Stopped update thread
2024-01-07 16:40:00 INFO (MainThread) [systembridgebackend.handlers.threads.media.MediaUpdateThread] Stopping thread
2024-01-07 16:40:00 INFO (MainThread) [systembridgebackend.server.Server] Update threads joined
2024-01-07 16:40:00 INFO (MainThread) [systembridgebackend.server.Server] Tasks cancelled
2024-01-07 16:40:00 INFO (MainThread) [systembridgebackend.server.Server] Stop API server
2024-01-07 16:40:00 INFO (MainThread) [systembridgebackend.server.Server] API server stopped
2024-01-07 16:40:00 INFO (MainThread) [systembridgebackend.server.Server] GUI threads joined
2024-01-07 16:40:00 INFO (MainThread) [systembridgebackend.server.Server] Tasks cleared
2024-01-07 16:40:00 INFO (MainThread) [systembridgebackend.server.Server] Event loop stopped
2024-01-07 16:40:00 CRITICAL (MainThread) [root] Unhandled error in application
Traceback (most recent call last):
  File "application.py", line 33, in application
  File "systembridgebackend/__init__.py", line 48, in __init__
    loop.run_until_complete(self._server.start())
  File "asyncio/base_events.py", line 682, in run_until_complete
RuntimeError: Event loop stopped before Future completed.
```

**Comment by timmo001** [comment]
2024-01-13 14:29:15 INFO (MainThread) [systembridgebackend.server.Server] GUI threads joined
2024-01-13 14:29:15 INFO (MainThread) [systembridgebackend.server.Server] Tasks cleared
2024-01-13 14:29:15 INFO (MainThread) [systembridgebackend.server.Server] Event loop stopped
2024-01-13 14:29:15 INFO (MainThread) [systembridgebackend.server.websocket.WebSocketHandler] Exit application called
2024-01-13 14:29:15 CRITICAL (MainThread) [root] Unhandled error in application
Traceback (most recent call last):
  File "application.py", line 33, in application
    BackendApplication(
  File "C:\Users\atims\AppData\Local\Programs\Python\Python312\Lib\site-packages\systembridgebackend\__init__.py", line 48, in __init__ 
    loop.run_until_complete(self._server.start())
  File "C:\Users\atims\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 682, in run_until_complete
    raise RuntimeError('Event loop stopped before Future completed.')
RuntimeError: Event loop stopped before Future completed.
2024-01-13 14:29:15 INFO (MainThread) [root] Application closed
