### ISSUE TITLE
Systembridge 4.0.4 won't open

### ISSUE THREAD

**Issue by n00bcodr** [timmo001/system-bridge#2959]
### Description

I have upgraded recently from 3.x to 4.0.4 and the application stopped opening since then.
I tried launching it from the command line but throws the below error.

```
pt@homeassistant:~$ systembridge
2024-03-29 13:31:25 INFO (MainThread) [root] Launching Backend
2024-03-29 13:31:25 INFO (MainThread) [systembridgebackend.Application] System Bridge 4.0.4: Startup
2024-03-29 13:31:25 INFO (MainThread) [systembridgebackend.Application] Your token is: 22b03cb2-b394-40de-a8af-3e07685b8897
2024-03-29 13:31:25 INFO (MainThread) [systembridgebackend.server.Server] Setup API app
2024-03-29 13:31:25 INFO (MainThread) [systembridgebackend.server.Server] Autostart enabled: False
2024-03-29 13:31:25 CRITICAL (MainThread) [root] Unhandled error in application
Traceback (most recent call last):
  File "application.py", line 34, in application
  File "systembridgebackend/__init__.py", line 42, in __init__
    self._server = Server(
                   ^^^^^^^
  File "systembridgebackend/server/__init__.py", line 81, in __init__
    autostart_disable()
  File "systembridgebackend/handlers/autostart/__init__.py", line 16, in autostart_disable
    autostart_linux_disable()
  File "systembridgebackend/handlers/autostart/linux.py", line 21, in autostart_linux_disable
    os.remove(path)
IsADirectoryError: [Errno 21] Is a directory: '/home/pt/.config/autostart/systembridge.desktop'
2024-03-29 13:31:25 INFO (MainThread) [root] Application closed: main
```

### What Platform / OS are you running?

Linux

### What version are you running?

4.0.4

**Comment by timmo001** [comment]
autostart replaced in upcoming 4.1.1

**Comment by n00bcodr** [comment]
Is there a workaround to start the application till 4.1.1 is released?

**Comment by timmo001** [comment]
No, there will be a release soon though
