### ISSUE TITLE
4.1.5 crashes when starting backend server

### ISSUE THREAD

**Issue by n00bcodr** [timmo001/system-bridge#2974]
### Description

I have previously raised #2959. 

Although after upgrading to 4.1.5, by completely uninstalling and removing all traces of 4.0.x System Bridge immediately crashes as soon as it opens. It also fails to open through command line.

```
pt@homeassistant:~$ system-bridge
Data path: /home/pt/.local/share/timmo001
Autostart: false
Data path: /home/pt/.local/share/timmo001
Data path: /home/pt/.local/share/timmo001
Checking backend server: http://127.0.0.1:9170/
Failed to connect to WebSocket server: Connection refused (os error 111)
Starting backend server from lib: /usr/lib/system-bridge/_up_/dist/systembridgebackend/systembridgebackend
Backend server started
2024-04-03 17:42:10 INFO (MainThread) [systembridgebackend.Application] System Bridge 4.1.5: Startup
2024-04-03 17:42:10 INFO (MainThread) [systembridgebackend.Application] Your token is: 2d36c18b-68a4-4758-b8c5-91703c00e860
2024-04-03 17:42:10 INFO (MainThread) [systembridgebackend.server.Server] Setup API app
2024-04-03 17:42:10 INFO (MainThread) [systembridgebackend.server.Server] Autostart enabled: False
2024-04-03 17:42:10 CRITICAL (MainThread) [root] Unhandled error in application
Traceback (most recent call last):
  File "backend.py", line 25, in main
  File "systembridgebackend/__init__.py", line 41, in __init__
    self._server = Server(
                   ^^^^^^^
  File "systembridgebackend/server/__init__.py", line 74, in __init__
    autostart_disable()
  File "systembridgebackend/handlers/autostart/__init__.py", line 16, in autostart_disable
    autostart_linux_disable()
  File "systembridgebackend/handlers/autostart/linux.py", line 21, in autostart_linux_disable
    os.remove(path)
IsADirectoryError: [Errno 21] Is a directory: '/home/pt/.config/autostart/systembridge.desktop'
Checking backend server: http://127.0.0.1:9170/
Failed to start the backend server
```

But when I try to open it as sudo, it opens through command line as long as the terminal is open.

```
pt@homeassistant:~$ sudo system-bridge

(system-bridge:1772003): libayatana-appindicator-WARNING **: 17:46:46.521: Unable to get the session bus: Failed to execute child process “dbus-launch” (No such file or directory)
Data path: /root/.local/share/timmo001
Autostart: true

(system-bridge:1772003): LIBDBUSMENU-GLIB-WARNING **: 17:46:46.529: Unable to get session bus: Failed to execute child process “dbus-launch” (No such file or directory)
Data path: /root/.local/share/timmo001
Data path: /root/.local/share/timmo001
Checking backend server: http://127.0.0.1:9170/
Failed to connect to WebSocket server: Connection refused (os error 111)
Starting backend server from lib: /usr/lib/system-bridge/_up_/dist/systembridgebackend/systembridgebackend
Backend server started
2024-04-03 17:46:47 INFO (MainThread) [systembridgebackend.Application] System Bridge 4.1.5: Startup
2024-04-03 17:46:47 INFO (MainThread) [systembridgebackend.Application] Your token is:  -9066-4fee-9cdb-394aeb7f88a7
2024-04-03 17:46:47 INFO (MainThread) [systembridgebackend.server.Server] Setup API app
2024-04-03 17:46:47 INFO (MainThread) [systembridgebackend.server.Server] Autostart enabled: True
2024-04-03 17:46:47 INFO (MainThread) [systembridgebackend.server.Server] Setup API server
2024-04-03 17:46:47 INFO (MainThread) [systembridgebackend.server.Server] Server initialised
2024-04-03 17:46:47 INFO (MainThread) [systembridgebackend.server.Server] Start server
2024-04-03 17:46:47 INFO (MainThread) [systembridgebackend.handlers.data.DataUpdate] Starting update data thread..
2024-04-03 17:46:47 INFO (Thread-2 (_run)) [systembridgebackend.handlers.threads.data.DataUpdateThread] Update took 0 seconds
2024-04-03 17:46:47 INFO (Thread-1) [systembridgebackend.handlers.threads.data.DataUpdateThread] Started update thread
2024-04-03 17:46:47 INFO (MainThread) [systembridgebackend.handlers.data.DataUpdate] Starting update media thread..
2024-04-03 17:46:47 INFO (Thread-2 (_run)) [systembridgebackend.handlers.threads.data.DataUpdateThread] Scheduled next update for: 2024-04-03 17:47:17.764689
2024-04-03 17:46:47 INFO (Thread-4 (_run)) [systembridgebackend.handlers.threads.media.MediaUpdateThread] Update took 0 seconds
2024-04-03 17:46:47 INFO (Thread-3) [systembridgebackend.handlers.threads.media.MediaUpdateThread] Started update thread
2024-04-03 17:46:47 INFO (Thread-2 (_run)) [systembridgebackend.modules.ModulesUpdate] Update data
2024-04-03 17:46:47 INFO (Thread-4 (_run)) [systembridgebackend.handlers.threads.media.MediaUpdateThread] Scheduled next update for: 2024-04-03 17:47:07.767146
2024-04-03 17:46:47 INFO (Thread-4 (_run)) [systembridgebackend.handlers.threads.media.MediaUpdateThread] Update finished, next run will be at: 2024-04-03 17:47:07.767146
2024-04-03 17:46:47 INFO (Thread-4 (_run)) [systembridgebackend.handlers.threads.media.MediaUpdateThread] Waiting for next update in 20.0 seconds
2024-04-03 17:46:47 INFO (MainThread) [uvicorn.error] Started server process [1772053]
2024-04-03 17:46:47 INFO (MainThread) [uvicorn.error] Waiting for application startup.
2024-04-03 17:46:47 INFO (MainThread) [systembridgebackend.server.Server] Register hotkeys
2024-04-03 17:46:47 INFO (MainThread) [systembridgebackend.server.Server] Found 0 hotkeys
2024-04-03 17:46:47 INFO (MainThread) [uvicorn.error] Application startup complete.
2024-04-03 17:46:47 INFO (MainThread) [uvicorn.error] Uvicorn running on http://0.0.0.0:9170 (Press CTRL+C to quit)
2024-04-03 17:46:47 INFO (Thread-2 (_run)) [systembridgebackend.modules.listeners.Listeners] Refresh data by module: sensors
2024-04-03 17:46:47 INFO (Thread-2 (_run)) [systembridgebackend.modules.ModulesUpdate] Request update module: system
2024-04-03 17:46:47 INFO (Thread-2 (_run)) [systembridgebackend.modules.system.SystemUpdate] Get latest version from GitHub
2024-04-03 17:46:48 INFO (Thread-2 (_run)) [systembridgebackend.modules.listeners.Listeners] Refresh data by module: system
2024-04-03 17:46:48 INFO (Thread-2 (_run)) [systembridgebackend.modules.ModulesUpdate] Request update module: battery
2024-04-03 17:46:48 ERROR (Thread-2 (_run)) [systembridgebackend.modules.battery.BatteryUpdate] could not convert string to float: '0% (should be ignored'
2024-04-03 17:46:48 INFO (Thread-2 (_run)) [systembridgebackend.modules.listeners.Listeners] Refresh data by module: battery
2024-04-03 17:46:49 INFO (Thread-2 (_run)) [systembridgebackend.modules.ModulesUpdate] Request update module: cpu
Checking backend server: http://127.0.0.1:9170/
2024-04-03 17:46:51 INFO (MainThread) [uvicorn.access] 127.0.0.1:54342 - "GET / HTTP/1.1" 200
Backend server is already running
Backend server is running
Waiting for 60 seconds before checking the backend server again
Data path: /root/.local/share/timmo001
Checking backend server: http://127.0.0.1:9170/
2024-04-03 17:46:51 INFO (MainThread) [uvicorn.access] 127.0.0.1:54346 - "GET / HTTP/1.1" 200
Backend server is already running
Waiting for 60 seconds before checking the backend server again
2024-04-03 17:46:53 INFO (Thread-2 (_run)) [systembridgebackend.modules.listeners.Listeners] Refresh data by module: cpu
2024-04-03 17:46:53 INFO (Thread-2 (_run)) [systembridgebackend.modules.ModulesUpdate] Request update module: disks
2024-04-03 17:46:53 INFO (Thread-2 (_run)) [systembridgebackend.modules.listeners.Listeners] Refresh data by module: disks
2024-04-03 17:46:54 INFO (Thread-2 (_run)) [systembridgebackend.modules.ModulesUpdate] Request update module: displays
2024-04-03 17:46:54 INFO (Thread-2 (_run)) [systembridgebackend.modules.listeners.Listeners] Refresh data by module: displays
2024-04-03 17:46:55 INFO (Thread-2 (_run)) [systembridgebackend.modules.ModulesUpdate] Request update module: gpus
2024-04-03 17:46:55 INFO (Thread-2 (_run)) [systembridgebackend.modules.listeners.Listeners] Refresh data by module: gpus
2024-04-03 17:46:56 INFO (Thread-2 (_run)) [systembridgebackend.modules.ModulesUpdate] Request update module: memory
2024-04-03 17:46:56 INFO (Thread-2 (_run)) [systembridgebackend.modules.listeners.Listeners] Refresh data by module: memory
2024-04-03 17:46:57 INFO (Thread-2 (_run)) [systembridgebackend.modules.ModulesUpdate] Request update module: networks
2024-04-03 17:46:58 INFO (Thread-2 (_run)) [systembridgebackend.modules.listeners.Listeners] Refresh data by module: networks
2024-04-03 17:46:58 INFO (Thread-2 (_run)) [systembridgebackend.modules.ModulesUpdate] Request update module: processes
2024-04-03 17:46:59 INFO (Thread-2 (_run)) [systembridgebackend.modules.listeners.Listeners] Refresh data by module: processes
2024-04-03 17:46:59 INFO (MainThread) [uvicorn.access] 192.168.68.168:57792 - "GET /information HTTP/1.1" 404
2024-04-03 17:46:59 INFO (AnyIO worker thread) [systembridgebackend.server.api] Authorized with Token Header
2024-04-03 17:46:59 INFO (AnyIO worker thread) [systembridgebackend.server.api] Token Header Result: True
2024-04-03 17:46:59 INFO (AnyIO worker thread) [systembridgebackend.server.api] Token Query Result: False
2024-04-03 17:46:59 INFO (MainThread) [uvicorn.access] 192.168.68.168:57792 - "GET /api/data/system HTTP/1.1" 200
2024-04-03 17:46:59 INFO (MainThread) [uvicorn.error] ('192.168.68.168', 57792) - "WebSocket /api/websocket" [accepted]
2024-04-03 17:46:59 INFO (MainThread) [uvicorn.error] connection open
2024-04-03 17:46:59 INFO (MainThread) [systembridgebackend.server.websocket.WebSocketHandler] Received: REGISTER_DATA_LISTENER
2024-04-03 17:46:59 INFO (MainThread) [systembridgebackend.server.websocket.WebSocketHandler] Registering data listener: f73b0c41-3e47-48d4-81ef-f3da4e46e2ca - ['battery', 'cpu', 'disks', 'displays', 'gpus', 'media', 'memory', 'processes', 'system']
2024-04-03 17:46:59 INFO (MainThread) [systembridgebackend.modules.listeners.Listeners] Added listener: f73b0c41-3e47-48d4-81ef-f3da4e46e2ca
2024-04-03 17:46:59 INFO (MainThread) [systembridgebackend.server.websocket.WebSocketHandler] Received: GET_DATA
2024-04-03 17:46:59 INFO (MainThread) [systembridgebackend.server.websocket.WebSocketHandler] Getting data: ['battery', 'cpu', 'disks', 'displays', 'gpus', 'media', 'memory', 'processes', 'system']
2024-04-03 17:46:59 INFO (Thread-2 (_run)) [systembridgebackend.modules.ModulesUpdate] Data update tasks started
2024-04-03 17:46:59 INFO (Thread-2 (_run)) [systembridgebackend.handlers.threads.data.DataUpdateThread] Update finished, next run will be at: 2024-04-03 17:47:17.764689
2024-04-03 17:46:59 INFO (Thread-2 (_run)) [systembridgebackend.handlers.threads.data.DataUpdateThread] Waiting for next update in 17.93 seconds
2024-04-03 17:47:07 INFO (Thread-4 (_run)) [systembridgebackend.handlers.threads.media.MediaUpdateThread] Update took 0 seconds
2024-04-03 17:47:07 INFO (Thread-4 (_run)) [systembridgebackend.handlers.threads.media.MediaUpdateThread] Scheduled next update for: 2024-04-03 17:47:27.768224
2024-04-03 17:47:07 INFO (Thread-4 (_run)) [systembridgebackend.handlers.threads.media.MediaUpdateThread] Update finished, next run will be at: 2024-04-03 17:47:27.768224
2024-04-03 17:47:07 INFO (Thread-4 (_run)) [systembridgebackend.handlers.threads.media.MediaUpdateThread] Waiting for next update in 20.0 seconds
2024-04-03 17:47:17 INFO (Thread-2 (_run)) [systembridgebackend.handlers.threads.data.DataUpdateThread] Update took 0 seconds
2024-04-03 17:47:17 INFO (Thread-2 (_run)) [systembridgebackend.handlers.threads.data.DataUpdateThread] Scheduled next update for: 2024-04-03 17:47:47.765762
2024-04-03 17:47:17 INFO (Thread-2 (_run)) [systembridgebackend.modules.ModulesUpdate] Update data
.
.
.
.
.
```

I am quite unsure if I am doing something wrong.

### What Platform / OS are you running?

Linux

### What version are you running?

4.1.5

**Comment by timmo001** [comment]
I've noticed this too, the launcher/gui appears to crash, but the backend is actually running

**Comment by n00bcodr** [comment]
I will check if it is in my processes, but I doubt it. Data is not being fetched by Home Assistant

**Comment by timmo001** [comment]
https://github.com/timmo001/system-bridge/pull/2982

**Comment by n00bcodr** [comment]
I completely uninstalled and installed 4.1.6

Now I have the below :(

```
pt@homeassistant:~$ system-bridge
Setting up backend server..
Data path: /home/pt/.local/share/timmo001
Data path: /home/pt/.local/share/timmo001
Creating settings file: {"api":{"token":"806edfdc-b93a-4215-9c0b-196c7456b08e","port":9170},"autostart":false,"keyboard_hotkeys":[],"log_level":"INFO","media":{"directories":[]}}
Checking backend server: http://127.0.0.1:9170/
Spawning application: /usr/lib/system-bridge/_up_/dist/systembridgebackend/systembridgebackend
Backend server started
Waiting for 60 seconds before checking the backend server again
Setting up backend server..
Data path: /home/pt/.local/share/timmo001
Checking backend server: http://127.0.0.1:9170/
Spawning application: /usr/lib/system-bridge/_up_/dist/systembridgebackend/systembridgebackend
Backend server started
Waiting for 60 seconds before checking the backend server again
Data path: /home/pt/.local/share/timmo001
Autostart: false
Data path: /home/pt/.local/share/timmo001
Failed to connect to WebSocket server: Connection refused (os error 111)
2024-04-04 18:51:38 INFO (MainThread) [systembridgebackend.Application] System Bridge 4.1.6: Startup
2024-04-04 18:51:38 INFO (MainThread) [systembridgebackend.Application] Your token is: 806edfdc-b93a-4215-9c0b-196c7456b08e
2024-04-04 18:51:38 INFO (MainThread) [systembridgebackend.server.Server] Setup API app
2024-04-04 18:51:38 INFO (MainThread) [systembridgebackend.server.Server] Autostart enabled: False
2024-04-04 18:51:38 CRITICAL (MainThread) [root] Unhandled error in application
Traceback (most recent call last):
  File "backend.py", line 25, in main
  File "systembridgebackend/__init__.py", line 41, in __init__
    self._server = Server(
                   ^^^^^^^
  File "systembridgebackend/server/__init__.py", line 74, in __init__
    autostart_disable()
  File "systembridgebackend/handlers/autostart/__init__.py", line 16, in autostart_disable
    autostart_linux_disable()
  File "systembridgebackend/handlers/autostart/linux.py", line 21, in autostart_linux_disable
    os.remove(path)
IsADirectoryError: [Errno 21] Is a directory: '/home/pt/.config/autostart/systembridge.desktop'
2024-04-04 18:51:38 INFO (MainThread) [systembridgebackend.Application] System Bridge 4.1.6: Startup
2024-04-04 18:51:38 INFO (MainThread) [systembridgebackend.Application] Your token is: 806edfdc-b93a-4215-9c0b-196c7456b08e
2024-04-04 18:51:38 INFO (MainThread) [systembridgebackend.server.Server] Setup API app
2024-04-04 18:51:38 INFO (MainThread) [systembridgebackend.server.Server] Autostart enabled: False
2024-04-04 18:51:38 CRITICAL (MainThread) [root] Unhandled error in application
Traceback (most recent call last):
  File "backend.py", line 25, in main
  File "systembridgebackend/__init__.py", line 41, in __init__
    self._server = Server(
                   ^^^^^^^
  File "systembridgebackend/server/__init__.py", line 74, in __init__
    autostart_disable()
  File "systembridgebackend/handlers/autostart/__init__.py", line 16, in autostart_disable
    autostart_linux_disable()
  File "systembridgebackend/handlers/autostart/linux.py", line 21, in autostart_linux_disable
    os.remove(path)
IsADirectoryError: [Errno 21] Is a directory: '/home/pt/.config/autostart/systembridge.desktop'
Creating window: settings
Data path: /home/pt/.local/share/timmo001
Exit requested
```

**Comment by timmo001** [comment]
Thanks for the updated logs, I have an idea this might be another issue you have found, but fixing #2984 might be a potential fix overall

**Comment by timmo001** [comment]
@n00bcodr Just took another look at your logs, take a look at `/home/pt/.config/autostart/systembridge.desktop`, the error is actually saying that systembridge.desktop which should be a file, is actually a directory.

You might have a better shot if you remove all the application and delete any lingering files in that path, then reinstall and try again

**Comment by n00bcodr** [comment]
Looks like that has fixed it @timmo001 !

Thank you!
