### ISSUE TITLE
Unable to load system module running as systemd service

### ISSUE THREAD

**Issue by eikw** [timmo001/system-bridge#2994]
### Description

If the application runs as systemd service, its unable to get the active username in the system module due to the nature of a service where this information is not available through the use of `os.getLogin()`.

Everything works if i start it as root user but as long as it runs as service it cant load the system module and therefor the connection to home assistant fails.

Proposed change:
use `pwd.getpwuid(os.getuid())[0]` inside `_get_active_user_name` for linux

### What Platform / OS are you running?

Linux

### What version are you running?

4.1.6

### Anything in the logs or a references that might be useful?

```txt
2024-04-05 17:37:21 ERROR (Thread-2 (_run)) [systembridgebackend.modules.ModulesUpdate] Failed to update module: system
Traceback (most recent call last):
  File "systembridgebackend/modules/__init__.py", line 74, in update_module
    module_data = await module_class.cls.update_all_data()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "systembridgebackend/modules/system.py", line 270, in update_all_data
    ) = await asyncio.gather(
        ^^^^^^^^^^^^^^^^^^^^^
  File "systembridgebackend/modules/system.py", line 42, in _get_active_user_name
    return os.getlogin()
           ^^^^^^^^^^^^^
OSError: [Errno 25] Inappropriate ioctl for device
2024-04-05 17:37:21 ERROR (Thread-2 (_run)) [systembridgebackend.modules.ModulesUpdate] Failed to update module: system
Traceback (most recent call last):
  File "systembridgebackend/modules/__init__.py", line 74, in update_module
    module_data = await module_class.cls.update_all_data()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "systembridgebackend/modules/system.py", line 270, in update_all_data
    ) = await asyncio.gather(
        ^^^^^^^^^^^^^^^^^^^^^
  File "systembridgebackend/modules/system.py", line 42, in _get_active_user_name
    return os.getlogin()
           ^^^^^^^^^^^^^
OSError: [Errno 25] Inappropriate ioctl for device
```

**Comment by timmo001** [comment]
Would this work on windows and linux?

**Comment by eikw** [comment]
I don't think so but it would be a solution for all possible Linux environments

**Comment by dwardu89** [comment]
What if you add in checks to get the os type before calling that?
e.g. 

```python
def is_platform_windows()
    return platform.system() == "Windows"
def is_platform_linux():
    return platform.system() == "Linux"
```

then have some if statement, if linux do that, else if windows do another, if macos do something else.

**Comment by dwardu89** [comment]
What if you add in checks to get the os type before calling that?
e.g. 

```python
def is_platform_windows()
    return platform.system() == "Windows"
def is_platform_linux():
    return platform.system() == "Linux"
```

then have some if statement, if linux do that, else if windows do another, if macos do something else.

**Comment by florian-asche** [comment]
Hi,

when trying to connect to system-bridge, installed on xubuntu i get the following error:

```
2024-04-06 14:15:37 INFO (Thread-2 (_run)) [systembridgebackend.modules.listeners.Listeners] Refresh data by module: sensors
2024-04-06 14:15:37 INFO (Thread-2 (_run)) [systembridgebackend.modules.listeners.Listeners] Refresh data by module: sensors
2024-04-06 14:15:37 INFO (Thread-2 (_run)) [systembridgebackend.modules.ModulesUpdate] Request update module: system
2024-04-06 14:15:37 INFO (Thread-2 (_run)) [systembridgebackend.modules.ModulesUpdate] Request update module: system
2024-04-06 14:15:37 INFO (Thread-2 (_run)) [systembridgebackend.modules.system.SystemUpdate] Get latest version from GitHub
2024-04-06 14:15:37 INFO (Thread-2 (_run)) [systembridgebackend.modules.system.SystemUpdate] Get latest version from GitHub
2024-04-06 14:15:37 ERROR (Thread-2 (_run)) [systembridgebackend.modules.ModulesUpdate] Failed to update module: system
Traceback (most recent call last):
  File "systembridgebackend/modules/__init__.py", line 74, in update_module
    module_data = await module_class.cls.update_all_data()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "systembridgebackend/modules/system.py", line 270, in update_all_data
    ) = await asyncio.gather(
        ^^^^^^^^^^^^^^^^^^^^^
  File "systembridgebackend/modules/system.py", line 42, in _get_active_user_name
    return os.getlogin()
           ^^^^^^^^^^^^^
OSError: [Errno 6] No such device or address
2024-04-06 14:15:37 ERROR (Thread-2 (_run)) [systembridgebackend.modules.ModulesUpdate] Failed to update module: system
Traceback (most recent call last):
  File "systembridgebackend/modules/__init__.py", line 74, in update_module
    module_data = await module_class.cls.update_all_data()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "systembridgebackend/modules/system.py", line 270, in update_all_data
    ) = await asyncio.gather(
        ^^^^^^^^^^^^^^^^^^^^^
  File "systembridgebackend/modules/system.py", line 42, in _get_active_user_name
    return os.getlogin()
           ^^^^^^^^^^^^^
OSError: [Errno 6] No such device or address
2024-04-06 14:15:38 INFO (Thread-2 (_run)) [systembridgebackend.modules.ModulesUpdate] Request update module: battery
2024-04-06 14:15:38 INFO (Thread-2 (_run)) [systembridgebackend.modules.ModulesUpdate] Request update module: battery
2024-04-06 14:15:38 INFO (Thread-2 (_run)) [systembridgebackend.modules.listeners.Listeners] Refresh data by module: battery
2024-04-06 14:15:38 INFO (Thread-2 (_run)) [systembridgebackend.modules.listeners.Listeners] Refresh data by module: battery
2024-04-06 14:15:39 INFO (Thread-2 (_run)) [systembridgebackend.modules.ModulesUpdate] Request update module: cpu
2024-04-06 14:15:39 INFO (Thread-2 (_run)) [systembridgebackend.modules.ModulesUpdate] Request update module: cpu
2024-04-06 14:15:42 INFO (MainThread) [uvicorn.error] ('192.168.33.6', 38380) - "WebSocket /api/websocket" [accepted]
2024-04-06 14:15:42 INFO (MainThread) [uvicorn.error] ('192.168.33.6', 38380) - "WebSocket /api/websocket" [accepted]
2024-04-06 14:15:42 INFO (MainThread) [uvicorn.error] connection open
2024-04-06 14:15:42 INFO (MainThread) [uvicorn.error] connection open
2024-04-06 14:15:42 INFO (MainThread) [systembridgebackend.server.websocket.WebSocketHandler] Received: GET_DATA
2024-04-06 14:15:42 INFO (MainThread) [systembridgebackend.server.websocket.WebSocketHandler] Received: GET_DATA
2024-04-06 14:15:42 INFO (MainThread) [systembridgebackend.server.websocket.WebSocketHandler] Getting data: ['system']

```

Not sure if there is a package missing, that needs to be installed or maybe its just something like this:
https://gitlab.com/librebob/athenaeum/-/merge_requests/17/diffs

**Comment by eikw** [comment]
> Hi,
> 
> when trying to connect to system-bridge, installed on xubuntu i get the following error:
> 
> ```
> 2024-04-06 14:15:37 INFO (Thread-2 (_run)) [systembridgebackend.modules.listeners.Listeners] Refresh data by module: sensors
> 2024-04-06 14:15:37 INFO (Thread-2 (_run)) [systembridgebackend.modules.listeners.Listeners] Refresh data by module: sensors
> 2024-04-06 14:15:37 INFO (Thread-2 (_run)) [systembridgebackend.modules.ModulesUpdate] Request update module: system
> 2024-04-06 14:15:37 INFO (Thread-2 (_run)) [systembridgebackend.modules.ModulesUpdate] Request update module: system
> 2024-04-06 14:15:37 INFO (Thread-2 (_run)) [systembridgebackend.modules.system.SystemUpdate] Get latest version from GitHub
> 2024-04-06 14:15:37 INFO (Thread-2 (_run)) [systembridgebackend.modules.system.SystemUpdate] Get latest version from GitHub
> 2024-04-06 14:15:37 ERROR (Thread-2 (_run)) [systembridgebackend.modules.ModulesUpdate] Failed to update module: system
> Traceback (most recent call last):
>   File "systembridgebackend/modules/__init__.py", line 74, in update_module
>     module_data = await module_class.cls.update_all_data()
>                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "systembridgebackend/modules/system.py", line 270, in update_all_data
>     ) = await asyncio.gather(
>         ^^^^^^^^^^^^^^^^^^^^^
>   File "systembridgebackend/modules/system.py", line 42, in _get_active_user_name
>     return os.getlogin()
>            ^^^^^^^^^^^^^
> OSError: [Errno 6] No such device or address
> 2024-04-06 14:15:37 ERROR (Thread-2 (_run)) [systembridgebackend.modules.ModulesUpdate] Failed to update module: system
> Traceback (most recent call last):
>   File "systembridgebackend/modules/__init__.py", line 74, in update_module
>     module_data = await module_class.cls.update_all_data()
>                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "systembridgebackend/modules/system.py", line 270, in update_all_data
>     ) = await asyncio.gather(
>         ^^^^^^^^^^^^^^^^^^^^^
>   File "systembridgebackend/modules/system.py", line 42, in _get_active_user_name
>     return os.getlogin()
>            ^^^^^^^^^^^^^
> OSError: [Errno 6] No such device or address
> 2024-04-06 14:15:38 INFO (Thread-2 (_run)) [systembridgebackend.modules.ModulesUpdate] Request update module: battery
> 2024-04-06 14:15:38 INFO (Thread-2 (_run)) [systembridgebackend.modules.ModulesUpdate] Request update module: battery
> 2024-04-06 14:15:38 INFO (Thread-2 (_run)) [systembridgebackend.modules.listeners.Listeners] Refresh data by module: battery
> 2024-04-06 14:15:38 INFO (Thread-2 (_run)) [systembridgebackend.modules.listeners.Listeners] Refresh data by module: battery
> 2024-04-06 14:15:39 INFO (Thread-2 (_run)) [systembridgebackend.modules.ModulesUpdate] Request update module: cpu
> 2024-04-06 14:15:39 INFO (Thread-2 (_run)) [systembridgebackend.modules.ModulesUpdate] Request update module: cpu
> 2024-04-06 14:15:42 INFO (MainThread) [uvicorn.error] ('192.168.33.6', 38380) - "WebSocket /api/websocket" [accepted]
> 2024-04-06 14:15:42 INFO (MainThread) [uvicorn.error] ('192.168.33.6', 38380) - "WebSocket /api/websocket" [accepted]
> 2024-04-06 14:15:42 INFO (MainThread) [uvicorn.error] connection open
> 2024-04-06 14:15:42 INFO (MainThread) [uvicorn.error] connection open
> 2024-04-06 14:15:42 INFO (MainThread) [systembridgebackend.server.websocket.WebSocketHandler] Received: GET_DATA
> 2024-04-06 14:15:42 INFO (MainThread) [systembridgebackend.server.websocket.WebSocketHandler] Received: GET_DATA
> 2024-04-06 14:15:42 INFO (MainThread) [systembridgebackend.server.websocket.WebSocketHandler] Getting data: ['system']
> ```
> 
> Not sure if there is a package missing, that needs to be installed or maybe its just something like this: https://gitlab.com/librebob/athenaeum/-/merge_requests/17/diffs

The suggested fix in the provided link seems to be the preferred solution as suggested in the docs of [getpass](https://docs.python.org/3/library/getpass.html#getpass.getuser).

I can implement and test this if needed.
