### ISSUE TITLE
Memory and CPU Errors & HA Timed out

### ISSUE THREAD

**Issue by Nidre** [timmo001/system-bridge#3037]
### Description

Hello, i have problem with 4 errors in log file:

```
2024-04-20 09:21:29 ERROR (Thread-2 (_run)) [systembridgebackend.modules.ModulesUpdate] Failed to update module: memory
Traceback (most recent call last):
  File "systembridgebackend\modules\__init__.py", line 74, in update_module
    module_data = await module_class.cls.update_all_data()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "systembridgebackend\modules\memory.py", line 30, in update_all_data
    swap, virtual = await asyncio.gather(
                    ^^^^^^^^^^^^^^^^^^^^^
  File "systembridgebackend\modules\memory.py", line 19, in _get_swap
    return swap_memory()
           ^^^^^^^^^^^^^
  File "psutil\__init__.py", line 2036, in swap_memory
  File "psutil\_pswindows.py", line 266, in swap_memory
RuntimeError: PdhAddEnglishCounterW failed. Performance counters may be disabled.

2024-04-20 09:21:51 ERROR (Thread-2 (_run)) [systembridgebackend.modules.sensors.SensorsUpdate] Windows sensors error for path: C:\Users\user\AppData\Local\System Bridge\_up_\dist\systembridgebackend\_internal\systembridgewindowssensors\bin\SystemBridgeWindowsSensors.exe
Traceback (most recent call last):
  File "systembridgebackend\modules\sensors.py", line 62, in _get_windows_sensors
    result = pipe.communicate()[0].decode()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcf in position 13952: invalid continuation byte

2024-04-20 09:21:57 ERROR (Thread-2 (_run)) [systembridgebackend.modules.ModulesUpdate] Failed to update module: cpu
Traceback (most recent call last):
  File "systembridgebackend\modules\__init__.py", line 74, in update_module
    module_data = await module_class.cls.update_all_data()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "systembridgebackend\modules\cpu.py", line 286, in update_all_data
    ) = await asyncio.gather(
        ^^^^^^^^^^^^^^^^^^^^^
  File "systembridgebackend\modules\cpu.py", line 46, in _get_load_average
    avg_tuple = getloadavg()
                ^^^^^^^^^^^^
  File "psutil\_pswindows.py", line 367, in getloadavg
RuntimeError: PdhAddEnglishCounterW failed. Performance counters may be disabled.

2024-04-20 09:25:51 WARNING (Thread-2 (_run)) [systembridgebackend.modules.disks.DisksUpdate] Error getting disk usage for: H:\
Traceback (most recent call last):
  File "systembridgebackend\modules\disks.py", line 38, in _get_usage
    return disk_usage(path)
           ^^^^^^^^^^^^^^^^
  File "psutil\__init__.py", line 2049, in disk_usage
  File "psutil\_pswindows.py", line 291, in disk_usage
PermissionError: [WinError 21] Device not ready: 'H:\\'
```

And i got 
![image](https://github.com/timmo001/system-bridge/assets/24737075/93b933a2-de00-41a5-a6e5-782f0dc7044d)
in HA, tried 9170 and 9171 ports.

### System Info
System Bridge [4.1.9](https://github.com/timmo001/system-bridge/releases/tag/4.1.9)
Windows 11 23H2 (22631.3447)
CPU: Ryzen 7 5800X 
RAM memory: 16GBx2
Swap memory: 
```
C: 12288-12288
D: None
E: None
F: None
```

H:\\ is cdrom

**Comment by timmo001** [comment]
`PdhAddEnglishCounterW failed. Performance counters may be disabled.`

A quick google search points me to this issue:

https://github.com/giampaolo/psutil/issues/2105

Try the steps there see if that fixes your issue

**Comment by Nidre** [comment]
It didn't help me, 4 errors are still there and still can't connect.
