### ISSUE TITLE
No data displayed

### ISSUE THREAD

**Issue by andjo** [timmo001/system-bridge#3049]
### Description

The view data window just display a spinner for everything except the media section.

### What Platform / OS are you running?

Windows

### What version are you running?

4.1.9

### Anything in the logs or a references that might be useful?

```txt
2024-04-28 20:56:02 INFO (MainThread) [uvicorn.access] 127.0.0.1:50432 - "GET / HTTP/1.1" 200
2024-04-28 20:56:02 INFO (Thread-2 (_run)) [systembridgebackend.handlers.threads.data.DataUpdateThread] Update took 0 seconds
2024-04-28 20:56:02 INFO (Thread-2 (_run)) [systembridgebackend.handlers.threads.data.DataUpdateThread] Scheduled next update for: 2024-04-28 20:56:32.983907
2024-04-28 20:56:02 INFO (Thread-2 (_run)) [systembridgebackend.modules.ModulesUpdate] Update data
2024-04-28 20:56:03 INFO (Thread-4 (_run)) [systembridgebackend.handlers.threads.media.MediaUpdateThread] Update took 0 seconds
2024-04-28 20:56:03 INFO (Thread-4 (_run)) [systembridgebackend.handlers.threads.media.MediaUpdateThread] Scheduled next update for: 2024-04-28 20:56:23.122941
2024-04-28 20:56:03 INFO (Thread-4 (_run)) [systembridgebackend.modules.media.Media] Updating media data
2024-04-28 20:56:03 INFO (Thread-4 (_run)) [systembridgebackend.modules.listeners.Listeners] Refresh data by module: media
2024-04-28 20:56:03 INFO (Thread-4 (_run)) [systembridgebackend.modules.listeners.Listeners] Listener: fd77d975-9f04-47bc-9f4b-e059e8a28b30 - ['battery', 'cpu', 'disks', 'displays', 'gpus', 'media', 'memory', 'networks', 'processes', 'sensors', 'system']
2024-04-28 20:56:03 INFO (Thread-4 (_run)) [systembridgebackend.modules.listeners.Listeners] Sending 'media' data to listener: fd77d975-9f04-47bc-9f4b-e059e8a28b30
2024-04-28 20:56:03 INFO (Thread-4 (_run)) [systembridgebackend.handlers.threads.media.MediaUpdateThread] Update finished, next run will be at: 2024-04-28 20:56:23.122941
2024-04-28 20:56:03 INFO (Thread-4 (_run)) [systembridgebackend.handlers.threads.media.MediaUpdateThread] Waiting for next update in 20.0 seconds
2024-04-28 20:56:04 ERROR (Thread-2 (_run)) [systembridgebackend.handlers.threads.data.DataUpdateThread] 'current_fan_speed_level'
Traceback (most recent call last):
  File "systembridgebackend\handlers\threads\update.py", line 44, in _run
    asyncio.new_event_loop().run_until_complete(self.update())
  File "asyncio\base_events.py", line 687, in run_until_complete
  File "systembridgebackend\handlers\threads\data.py", line 29, in update
    await self._update_cls.update_data()
  File "systembridgebackend\modules\__init__.py", line 88, in update_data
    sensors_data = await sensors_update.update_all_data()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "systembridgebackend\modules\sensors.py", line 178, in update_all_data
    current_fan_speed_level=gpu["current_fan_speed_level"],
                            ~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'current_fan_speed_level'
2024-04-28 20:56:04 INFO (Thread-2 (_run)) [systembridgebackend.handlers.threads.data.DataUpdateThread] Update finished, next run will be at: 2024-04-28 20:56:32.983907
2024-04-28 20:56:04 INFO (Thread-2 (_run)) [systembridgebackend.handlers.threads.data.DataUpdateThread] Waiting for next update in 28.07 seconds
```

**Comment by andjo** [comment]
bump

**Comment by andjo** [comment]
bump
