### ISSUE TITLE
Latest Windows Updates breaks SB with HA

### ISSUE THREAD

**Issue by DeFlanko** [timmo001/system-bridge#3211]
### Description

"System" is now spinning no data. 

![image](https://github.com/user-attachments/assets/7b91ff76-8608-4445-b8d4-403fc8494d4b)

### What Platform / OS are you running?

Windows

### How is System Bridge Being Ran?

Standalone (executable)

### What version are you running?

4.1.10

### Anything in the logs or a references that might be useful?

```txt
#3152 might be related
```

**Comment by DeFlanko** [comment]
```Logs
2024-08-27 21:38:42 INFO (Thread-2 (_run)) [systembridgebackend.handlers.threads.data.DataUpdateThread] Update took 0 seconds
2024-08-27 21:38:42 INFO (Thread-2 (_run)) [systembridgebackend.handlers.threads.data.DataUpdateThread] Scheduled next update for: 2024-08-27 21:39:12.058849
2024-08-27 21:38:42 INFO (Thread-2 (_run)) [systembridgebackend.modules.ModulesUpdate] Update data
2024-08-27 21:38:44 INFO (Thread-2 (_run)) [systembridgebackend.modules.listeners.Listeners] Refresh data by module: sensors
2024-08-27 21:38:44 INFO (Thread-2 (_run)) [systembridgebackend.modules.listeners.Listeners] Listener: d87c430b-dd7c-4d7e-b397-9becfe30b6c2 - ['battery', 'cpu', 'disks', 'displays', 'gpus', 'media', 'memory', 'networks', 'processes', 'sensors', 'system']
2024-08-27 21:38:44 INFO (Thread-2 (_run)) [systembridgebackend.modules.listeners.Listeners] Sending 'sensors' data to listener: d87c430b-dd7c-4d7e-b397-9becfe30b6c2
2024-08-27 21:38:44 INFO (Thread-2 (_run)) [systembridgebackend.modules.ModulesUpdate] Request update module: system
2024-08-27 21:38:44 INFO (Thread-2 (_run)) [systembridgebackend.modules.system.SystemUpdate] Get latest version from GitHub
2024-08-27 21:38:44 ERROR (Thread-2 (_run)) [systembridgebackend.modules.ModulesUpdate] Failed to update module: system
Traceback (most recent call last):
  File "aiohttp\connector.py", line 1073, in _wrap_create_connection
  File "aiohappyeyeballs\impl.py", line 104, in start_connection
  File "aiohappyeyeballs\impl.py", line 81, in start_connection
  File "aiohappyeyeballs\impl.py", line 166, in _connect_sock
  File "asyncio\proactor_events.py", line 729, in sock_connect
  File "asyncio\windows_events.py", line 803, in _poll
  File "asyncio\windows_events.py", line 599, in finish_connect
PermissionError: [WinError 5] Access is denied

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "systembridgebackend\modules\__init__.py", line 74, in update_module
    module_data = await module_class.cls.update_all_data()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "systembridgebackend\modules\system.py", line 319, in update_all_data
    ) = await asyncio.gather(
        ^^^^^^^^^^^^^^^^^^^^^
  File "systembridgebackend\modules\system.py", line 273, in _get_version_latest
    rate_limit_remaining = await self._check_rate_limit()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "systembridgebackend\modules\system.py", line 259, in _check_rate_limit
    async with aiohttp.ClientSession() as session, session.get(
  File "aiohttp\client.py", line 1353, in __aenter__
  File "aiohttp\client.py", line 657, in _request
  File "aiohttp\connector.py", line 564, in connect
  File "aiohttp\connector.py", line 975, in _create_connection
  File "aiohttp\connector.py", line 1350, in _create_direct_connection
  File "aiohttp\connector.py", line 1319, in _create_direct_connection
  File "aiohttp\connector.py", line 1088, in _wrap_create_connection
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host api.github.com:443 ssl:default [Access is denied]
2024-08-27 21:38:45 INFO (Thread-2 (_run)) [systembridgebackend.modules.ModulesUpdate] Request update module: battery
2024-08-27 21:38:45 INFO (Thread-2 (_run)) [systembridgebackend.modules.listeners.Listeners] Refresh data by module: battery
2024-08-27 21:38:45 INFO (Thread-2 (_run)) [systembridgebackend.modules.listeners.Listeners] Listener: d87c430b-dd7c-4d7e-b397-9becfe30b6c2 - ['battery', 'cpu', 'disks', 'displays', 'gpus', 'media', 'memory', 'networks', 'processes', 'sensors', 'system']
2024-08-27 21:38:45 INFO (Thread-2 (_run)) [systembridgebackend.modules.listeners.Listeners] Sending 'battery' data to listener: d87c430b-dd7c-4d7e-b397-9becfe30b6c2
2024-08-27 21:38:46 INFO (Thread-2 (_run)) [systembridgebackend.modules.ModulesUpdate] Request update module: cpu
2024-08-27 21:38:50 INFO (Thread-2 (_run)) [systembridgebackend.modules.listeners.Listeners] Refresh data by module: cpu
2024-08-27 21:38:50 INFO (Thread-2 (_run)) [systembridgebackend.modules.listeners.Listeners] Listener: d87c430b-dd7c-4d7e-b397-9becfe30b6c2 - ['battery', 'cpu', 'disks', 'displays', 'gpus', 'media', 'memory', 'networks', 'processes', 'sensors', 'system']
2024-08-27 21:38:50 INFO (Thread-2 (_run)) [systembridgebackend.modules.listeners.Listeners] Sending 'cpu' data to listener: d87c430b-dd7c-4d7e-b397-9becfe30b6c2
2024-08-27 21:38:50 INFO (Thread-2 (_run)) [systembridgebackend.modules.ModulesUpdate] Request update module: disks
2024-08-27 21:38:50 WARNING (Thread-2 (_run)) [systembridgebackend.modules.disks.DisksUpdate] Error getting disk usage for: G:\
Traceback (most recent call last):
  File "systembridgebackend\modules\disks.py", line 38, in _get_usage
    return disk_usage(path)
           ^^^^^^^^^^^^^^^^
  File "psutil\__init__.py", line 2040, in disk_usage
  File "psutil\_pswindows.py", line 290, in disk_usage
PermissionError: [WinError 5] Access is denied: 'G:\\'
2024-08-27 21:38:50 INFO (Thread-2 (_run)) [systembridgebackend.modules.listeners.Listeners] Refresh data by module: disks
2024-08-27 21:38:50 INFO (Thread-2 (_run)) [systembridgebackend.modules.listeners.Listeners] Listener: d87c430b-dd7c-4d7e-b397-9becfe30b6c2 - ['battery', 'cpu', 'disks', 'displays', 'gpus', 'media', 'memory', 'networks', 'processes', 'sensors', 'system']
2024-08-27 21:38:50 INFO (Thread-2 (_run)) [systembridgebackend.modules.listeners.Listeners] Sending 'disks' data to listener: d87c430b-dd7c-4d7e-b397-9becfe30b6c2
2024-08-27 21:38:51 INFO (Thread-2 (_run)) [systembridgebackend.modules.ModulesUpdate] Request update module: displays
2024-08-27 21:38:51 INFO (Thread-2 (_run)) [systembridgebackend.modules.listeners.Listeners] Refresh data by module: displays
2024-08-27 21:38:51 INFO (Thread-2 (_run)) [systembridgebackend.modules.listeners.Listeners] Listener: d87c430b-dd7c-4d7e-b397-9becfe30b6c2 - ['battery', 'cpu', 'disks', 'displays', 'gpus', 'media', 'memory', 'networks', 'processes', 'sensors', 'system']
2024-08-27 21:38:51 INFO (Thread-2 (_run)) [systembridgebackend.modules.listeners.Listeners] Sending 'displays' data to listener: d87c430b-dd7c-4d7e-b397-9becfe30b6c2
2024-08-27 21:38:52 INFO (Thread-2 (_run)) [systembridgebackend.modules.ModulesUpdate] Request update module: gpus
2024-08-27 21:38:52 INFO (Thread-2 (_run)) [systembridgebackend.modules.listeners.Listeners] Refresh data by module: gpus
2024-08-27 21:38:52 INFO (Thread-2 (_run)) [systembridgebackend.modules.listeners.Listeners] Listener: d87c430b-dd7c-4d7e-b397-9becfe30b6c2 - ['battery', 'cpu', 'disks', 'displays', 'gpus', 'media', 'memory', 'networks', 'processes', 'sensors', 'system']
2024-08-27 21:38:52 INFO (Thread-2 (_run)) [systembridgebackend.modules.listeners.Listeners] Sending 'gpus' data to listener: d87c430b-dd7c-4d7e-b397-9becfe30b6c2
2024-08-27 21:38:52 INFO (Thread-4 (_run)) [systembridgebackend.handlers.threads.media.MediaUpdateThread] Update took 0 seconds
2024-08-27 21:38:52 INFO (Thread-4 (_run)) [systembridgebackend.handlers.threads.media.MediaUpdateThread] Scheduled next update for: 2024-08-27 21:39:12.185089
2024-08-27 21:38:52 ERROR (Thread-4 (_run)) [systembridgebackend.modules.media.Media] Error updating media info: [WinError -2147023836] The specified service does not exist as an installed service
2024-08-27 21:38:52 INFO (Thread-4 (_run)) [systembridgebackend.modules.media.Media] Updating media data
2024-08-27 21:38:52 INFO (Thread-4 (_run)) [systembridgebackend.modules.listeners.Listeners] Refresh data by module: media
2024-08-27 21:38:52 INFO (Thread-4 (_run)) [systembridgebackend.modules.listeners.Listeners] Listener: d87c430b-dd7c-4d7e-b397-9becfe30b6c2 - ['battery', 'cpu', 'disks', 'displays', 'gpus', 'media', 'memory', 'networks', 'processes', 'sensors', 'system']
2024-08-27 21:38:52 INFO (Thread-4 (_run)) [systembridgebackend.modules.listeners.Listeners] Sending 'media' data to listener: d87c430b-dd7c-4d7e-b397-9becfe30b6c2
2024-08-27 21:38:52 INFO (Thread-4 (_run)) [systembridgebackend.handlers.threads.media.MediaUpdateThread] Update finished, next run will be at: 2024-08-27 21:39:12.185089
2024-08-27 21:38:52 INFO (Thread-4 (_run)) [systembridgebackend.handlers.threads.media.MediaUpdateThread] Waiting for next update in 19.99 seconds
2024-08-27 21:38:53 INFO (Thread-2 (_run)) [systembridgebackend.modules.ModulesUpdate] Request update module: memory
2024-08-27 21:38:53 INFO (Thread-2 (_run)) [systembridgebackend.modules.listeners.Listeners] Refresh data by module: memory
2024-08-27 21:38:53 INFO (Thread-2 (_run)) [systembridgebackend.modules.listeners.Listeners] Listener: d87c430b-dd7c-4d7e-b397-9becfe30b6c2 - ['battery', 'cpu', 'disks', 'displays', 'gpus', 'media', 'memory', 'networks', 'processes', 'sensors', 'system']
2024-08-27 21:38:53 INFO (Thread-2 (_run)) [systembridgebackend.modules.listeners.Listeners] Sending 'memory' data to listener: d87c430b-dd7c-4d7e-b397-9becfe30b6c2
2024-08-27 21:38:54 INFO (Thread-2 (_run)) [systembridgebackend.modules.ModulesUpdate] Request update module: networks
2024-08-27 21:38:54 INFO (Thread-2 (_run)) [systembridgebackend.modules.listeners.Listeners] Refresh data by module: networks
2024-08-27 21:38:54 INFO (Thread-2 (_run)) [systembridgebackend.modules.listeners.Listeners] Listener: d87c430b-dd7c-4d7e-b397-9becfe30b6c2 - ['battery', 'cpu', 'disks', 'displays', 'gpus', 'media', 'memory', 'networks', 'processes', 'sensors', 'system']
2024-08-27 21:38:54 INFO (Thread-2 (_run)) [systembridgebackend.modules.listeners.Listeners] Sending 'networks' data to listener: d87c430b-dd7c-4d7e-b397-9becfe30b6c2

```

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by DeFlanko** [comment]
Oddly enough... after 3 reboots of the Host machine.. it started working again.... im not sure whats going on here... closing this.
