### ISSUE TITLE
"Error: spawn wmic ENOENT" when trying to GET and/or PUT /display 

### ISSUE THREAD

**Issue by timmo001** [timmo001/system-bridge#433]
### Discussed in https://github.com/timmo001/system-bridge/discussions/359

<div type='discussions-op-text'>

<sup>Originally posted by **boardwarp** June  3, 2021</sup>
Hello, I just installed System-Bridge today and found that most of the GET endpoints are working great, but /display doesn't seem to work. A few seconds after sending the request, the S-B settings window crashes although several of its processes remain running, and no response is received in Postman. The errors below also appear in the log. Since I've never had this working before I'm not sure if it's a support issue or a possible bug so I thought I'd ask here first.

```
2021-06-03 20:20:22 error: Error: spawn wmic ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
2021-06-03 20:20:22 error: Error: spawn wmic ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
2021-06-03 20:20:22 error: Error: spawn wmic ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```</div>

**Comment by timmo001** [comment]
Removed brightness module from the app in #432
