### ISSUE TITLE
Package JSON doesn't exist in built app

### ISSUE THREAD

**Issue by timmo001** [timmo001/system-bridge#441]
### Description

Stops Tray from being shown and information endpoint to break

### What Platform / OS are you running?

Windows

### Anything in the logs or a references that might be useful?

```txt
(node:26540) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'package.json'
    at Object.openSync (fs.js:498:3)
    at Object.openSync (pkg/prelude/bootstrap.js:696:32)
    at Object.readFileSync (fs.js:394:35)
    at Object.readFileSync (pkg/prelude/bootstrap.js:982:36)
    at getVersion (C:\snapshot\system-bridge\dist\common.js)
    at Object.getUpdates (C:\snapshot\system-bridge\dist\common.js)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Tray.setupTray (C:\snapshot\system-bridge\dist\tray.js)
(Use `system-bridge --trace-warnings ...` to show where the warning was created)
(node:26540) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:26540) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by timmo001** [comment]
Resolved in #461
