### ISSUE TITLE
App crashes occasionally over time - Too many open files

### ISSUE THREAD

**Issue by timmo001** [timmo001/system-bridge#739]
### Description

![image](https://user-images.githubusercontent.com/28114703/130361662-14ab2722-87f7-43a5-9746-7a6c3265aa77.png)

### What Platform / OS are you running?

Windows

### What version are you running?

DEV 2.6.0

**Comment by timmo001** [comment]
Still occurring after #749 

Less often, but still crashes after a few hours

**Comment by timmo001** [comment]
Monitoring after latest change

**Comment by timmo001** [comment]
Started server at 09:34:53

Crashed at 15:17:14

```bash
internal/fs/utils.js:314
    throw err;
    ^

Error: EMFILE: too many open files, open 'C:\Users\Aidan Timson\AppData\Local\System Bridge\system-bridge.exe'
    at Object.openSync (fs.js:498:3)
    at internal/bootstrap/pkg.js:35:17
    at internal/bootstrap/pkg.js:43:4
    at internal/bootstrap/pkg.js:44:2 {
  errno: -4066,
  syscall: 'open',
  code: 'EMFILE',
  path: 'C:\\Users\\Aidan Timson\\AppData\\Local\\System Bridge\\system-bridge.exe'
}
```

**Comment by timmo001** [comment]
Process manager created, should restart the api if it crashes as a workaround

**Comment by timmo001** [comment]
Resolved
