### ISSUE TITLE
Startup blocks windows UI

### ISSUE THREAD

**Issue by dlangerm** [timmo001/system-bridge#828]
### Description

The title says it all. Currently on the Windows 11 release preview, but this issue also happened with windows 10. When the app runs on startup, my entire desktop environment freezes for a few seconds. There are a ton of strange errors in the logs as well (why is it looking for an executable in `system32`?) and it seems like the startup process is having trouble with pathing.

Startup log attached.

I've tried a clean reinstall etc. It doesn't seem to help. Despite the errors in the logs, the system seems to work fine, I have it integrated with Home Assistant and the sensors show up fine.

### What Platform / OS are you running?

Windows

### What version are you running?

2.5.0

### Anything in the logs or a references that might be useful?

```txt
2021-09-20 09:30:51 info: -----------------------------------------------------------------------------------------------------------------------
2021-09-20 09:30:51 info: System Bridge 2.5.0: ["C:\\Users\\xxx\\AppData\\Local\\System Bridge\\system-bridge.exe","C:\\snapshot\\system-bridge\\dist\\main.js"] - undefined
2021-09-20 09:30:51 info: -----------------------------------------------------------------------------------------------------------------------
2021-09-20 09:30:51 info: Main - Open Tray: C:\Users\xxx\AppData\Local\System Bridge\system-bridge-tray.exe
2021-09-20 09:30:51 info: MQTT - Setup
2021-09-20 09:30:51 info: Main - API started on port 9170
2021-09-20 09:30:54 info: Main - Launch on startup: true - enabled - C:\Users\xxx\AppData\Local\System Bridge\system-bridge.exe
2021-09-20 09:30:54 info: Main - RTC broker created on path /rtc
2021-09-20 09:30:54 info: Events - Listening
2021-09-20 09:30:55 info: WebSocket - New client registered
2021-09-20 09:30:56 info: -----------------------------------------------------------------------------------------------------------------------
2021-09-20 09:30:56 info: System Bridge - Tray 2.5.0: ["C:\\Users\\xxx\\AppData\\Local\\System Bridge\\system-bridge-tray.exe","C:\\snapshot\\system-bridge\\tray\\dist\\tray\\src\\tray.js"] - undefined
2021-09-20 09:30:56 info: -----------------------------------------------------------------------------------------------------------------------
2021-09-20 09:30:56 info: Tray - Create Tray
2021-09-20 09:30:56 info: Tray - Started
2021-09-20 09:31:01 warn: Error: dns service error: service not running
    at objectToTXTRecord (C:\snapshot\system-bridge\node_modules\mdns\lib\advertisement.js:90:12)
    at new Advertisement (C:\snapshot\system-bridge\node_modules\mdns\lib\advertisement.js:36:17)
    at Object.create (C:\snapshot\system-bridge\node_modules\mdns\lib\advertisement.js:64:10)
    at Server.<anonymous> (C:\snapshot\system-bridge\dist\main.js)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
2021-09-20 09:31:27 error: Command failed with exit code 1: C:\WINDOWS\system32\WindowsSensors\SystemBridgeWindowsSensors.exe {"gpu":true}
The system cannot find the path specified.
2021-09-20 09:31:27 error: Command failed with exit code 1: C:\WINDOWS\system32\WindowsSensors\SystemBridgeWindowsSensors.exe {"gpu":true}
The system cannot find the path specified.
2021-09-20 09:31:28 error: Command failed with exit code 1: C:\WINDOWS\system32\WindowsSensors\SystemBridgeWindowsSensors.exe {"cpu":true}
The system cannot find the path specified.
2021-09-20 09:31:54 error: Command failed with exit code 1: C:\WINDOWS\system32\WindowsSensors\SystemBridgeWindowsSensors.exe {"cpu":true}
The system cannot find the path specified.
2021-09-20 09:31:57 error: Command failed with exit code 1: C:\WINDOWS\system32\WindowsSensors\SystemBridgeWindowsSensors.exe {"gpu":true}
The system cannot find the path specified.
2021-09-20 09:31:57 error: Command failed with exit code 1: C:\WINDOWS\system32\WindowsSensors\SystemBridgeWindowsSensors.exe {"gpu":true}
The system cannot find the path specified.
2021-09-20 09:31:58 error: Command failed with exit code 1: C:\WINDOWS\system32\WindowsSensors\SystemBridgeWindowsSensors.exe {"cpu":true}
The system cannot find the path specified.
2021-09-20 09:32:27 error: Command failed with exit code 1: C:\WINDOWS\system32\WindowsSensors\SystemBridgeWindowsSensors.exe {"gpu":true}
The system cannot find the path specified.
2021-09-20 09:32:27 error: Command failed with exit code 1: C:\WINDOWS\system32\WindowsSensors\SystemBridgeWindowsSensors.exe {"gpu":true}
The system cannot find the path specified.
2021-09-20 09:32:28 error: Command failed with exit code 1: C:\WINDOWS\system32\WindowsSensors\SystemBridgeWindowsSensors.exe {"cpu":true}
The system cannot find the path specified.
2021-09-20 09:32:57 error: Command failed with exit code 1: C:\WINDOWS\system32\WindowsSensors\SystemBridgeWindowsSensors.exe {"gpu":true}
The system cannot find the path specified.
2021-09-20 09:32:57 error: Command failed with exit code 1: C:\WINDOWS\system32\WindowsSensors\SystemBridgeWindowsSensors.exe {"gpu":true}
The system cannot find the path specified.
2021-09-20 09:32:59 error: Command failed with exit code 1: C:\WINDOWS\system32\WindowsSensors\SystemBridgeWindowsSensors.exe {"cpu":true}
The system cannot find the path specified.
2021-09-20 09:33:00 error: Command failed with exit code 1: C:\WINDOWS\system32\WindowsSensors\SystemBridgeWindowsSensors.exe {"cpu":true}
The system cannot find the path specified.
2021-09-20 09:33:27 error: Command failed with exit code 1: C:\WINDOWS\system32\WindowsSensors\SystemBridgeWindowsSensors.exe {"gpu":true}
The system cannot find the path specified.
2021-09-20 09:33:27 error: Command failed with exit code 1: C:\WINDOWS\system32\WindowsSensors\SystemBridgeWindowsSensors.exe {"gpu":true}
The system cannot find the path specified.
2021-09-20 09:33:28 error: Command failed with exit code 1: C:\WINDOWS\system32\WindowsSensors\SystemBridgeWindowsSensors.exe {"cpu":true}
The system cannot find the path specified.
2021-09-20 09:33:57 error: Command failed with exit code 1: C:\WINDOWS\system32\WindowsSensors\SystemBridgeWindowsSensors.exe {"gpu":true}
The system cannot find the path specified.
2021-09-20 09:33:57 error: Command failed with exit code 1: C:\WINDOWS\system32\WindowsSensors\SystemBridgeWindowsSensors.exe {"gpu":true}
The system cannot find the path specified.
2021-09-20 09:33:59 error: Command failed with exit code 1: C:\WINDOWS\system32\WindowsSensors\SystemBridgeWindowsSensors.exe {"cpu":true}
The system cannot find the path specified.
2021-09-20 09:34:00 error: Command failed with exit code 1: C:\WINDOWS\system32\WindowsSensors\SystemBridgeWindowsSensors.exe {"cpu":true}
The system cannot find the path specified.
2021-09-20 09:34:27 error: Command failed with exit code 1: C:\WINDOWS\system32\WindowsSensors\SystemBridgeWindowsSensors.exe {"gpu":true}
The system cannot find the path specified.
2021-09-20 09:34:27 error: Command failed with exit code 1: C:\WINDOWS\system32\WindowsSensors\SystemBridgeWindowsSensors.exe {"gpu":true}
The system cannot find the path specified.
2021-09-20 09:34:28 error: Command failed with exit code 1: C:\WINDOWS\system32\WindowsSensors\SystemBridgeWindowsSensors.exe {"cpu":true}
The system cannot find the path specified.
2021-09-20 09:34:44 info: -----------------------------------------------------------------------------------------------------------------------
2021-09-20 09:34:44 info: System Bridge 2.5.0: ["C:\\Users\\xxx\\AppData\\Local\\System Bridge\\system-bridge.exe","C:\\snapshot\\system-bridge\\dist\\main.js"] - undefined
2021-09-20 09:34:44 info: -----------------------------------------------------------------------------------------------------------------------
2021-09-20 09:34:44 info: Main - Open Tray: C:\Users\xxx\AppData\Local\System Bridge\system-bridge-tray.exe
2021-09-20 09:34:45 error: Error: listen EADDRINUSE: address already in use :::9172
    at Server.setupListenHandle [as _listen2] (net.js:1320:16)
    at listenInCluster (net.js:1368:12)
    at Server.listen (net.js:1454:7)
    at new WebSocketServer (C:\snapshot\system-bridge\node_modules\ws\lib\websocket-server.js:90:20)
    at WsAdapter.create (C:\snapshot\system-bridge\dist\api\ws-adapter.js)
    at SocketServerProvider.createSocketServer (C:\snapshot\system-bridge\node_modules\@nestjs\websockets\socket-server-provider.js:27:34)
    at SocketServerProvider.scanForSocketServer (C:\snapshot\system-bridge\node_modules\@nestjs\websockets\socket-server-provider.js:22:20)
    at WebSocketsController.subscribeToServerEvents (C:\snapshot\system-bridge\node_modules\@nestjs\websockets\web-sockets-controller.js:34:60)
    at WebSocketsController.connectGatewayToServer (C:\snapshot\system-bridge\node_modules\@nestjs\websockets\web-sockets-controller.js:25:14)
    at SocketModule.connectGatewayToServer (C:\snapshot\system-bridge\node_modules\@nestjs\websockets\socket-module.js:46:35)
2021-09-20 09:34:45 error: Error: listen EADDRINUSE: address already in use :::9172
    at Server.setupListenHandle [as _listen2] (net.js:1320:16)
    at listenInCluster (net.js:1368:12)
    at Server.listen (net.js:1454:7)
    at new WebSocketServer (C:\snapshot\system-bridge\node_modules\ws\lib\websocket-server.js:90:20)
    at WsAdapter.create (C:\snapshot\system-bridge\dist\api\ws-adapter.js)
    at SocketServerProvider.createSocketServer (C:\snapshot\system-bridge\node_modules\@nestjs\websockets\socket-server-provider.js:27:34)
    at SocketServerProvider.scanForSocketServer (C:\snapshot\system-bridge\node_modules\@nestjs\websockets\socket-server-provider.js:22:20)
    at WebSocketsController.subscribeToServerEvents (C:\snapshot\system-bridge\node_modules\@nestjs\websockets\web-sockets-controller.js:34:60)
    at WebSocketsController.connectGatewayToServer (C:\snapshot\system-bridge\node_modules\@nestjs\websockets\web-sockets-controller.js:25:14)
    at SocketModule.connectGatewayToServer (C:\snapshot\system-bridge\node_modules\@nestjs\websockets\socket-module.js:46:35)
2021-09-20 09:34:45 error: Error: listen EADDRINUSE: address already in use :::9170
    at Server.setupListenHandle [as _listen2] (net.js:1320:16)
    at listenInCluster (net.js:1368:12)
    at Server.listen (net.js:1454:7)
    at ExpressAdapter.listen (C:\snapshot\system-bridge\node_modules\@nestjs\platform-express\adapters\express-adapter.js:50:32)
    at C:\snapshot\system-bridge\node_modules\@nestjs\core\nest-application.js:168:46
    at new Promise (<anonymous>)
    at NestApplication.listen (C:\snapshot\system-bridge\node_modules\@nestjs\core\nest-application.js:157:16)
    at async startServer (C:\snapshot\system-bridge\dist\main.js)
2021-09-20 09:34:45 info: MQTT - Setup
2021-09-20 09:34:46 info: -----------------------------------------------------------------------------------------------------------------------
2021-09-20 09:34:46 info: System Bridge - Tray 2.5.0: ["C:\\Users\\xxx\\AppData\\Local\\System Bridge\\system-bridge-tray.exe","C:\\snapshot\\system-bridge\\tray\\dist\\tray\\src\\tray.js"] - undefined
2021-09-20 09:34:46 info: -----------------------------------------------------------------------------------------------------------------------
2021-09-20 09:34:46 info: Tray - Create Tray
2021-09-20 09:34:46 info: Tray - Started
2021-09-20 09:34:57 error: Command failed with exit code 1: C:\WINDOWS\system32\WindowsSensors\SystemBridgeWindowsSensors.exe {"gpu":true}
The system cannot find the path specified.
2021-09-20 09:34:57 error: Command failed with exit code 1: C:\WINDOWS\system32\WindowsSensors\SystemBridgeWindowsSensors.exe {"gpu":true}
The system cannot find the path specified.
2021-09-20 09:34:58 error: Command failed with exit code 1: C:\WINDOWS\system32\WindowsSensors\SystemBridgeWindowsSensors.exe {"cpu":true}
The system cannot find the path specified.
2021-09-20 09:35:02 error: Command failed with exit code 1: C:\WINDOWS\system32\WindowsSensors\SystemBridgeWindowsSensors.exe {"cpu":true}
The system cannot find the path specified.
```

### Additional information

Hardware: 
- RTX 3090
- Ryzen 3900X

**Comment by timmo001** [comment]
Please update to [v2.6.0](https://github.com/timmo001/system-bridge/releases). There have been a lot of changes and fixes which will hopefully help fix and/or diagnose your issue.

If you still have issues, can you please update your logs and version in the description

**Comment by timmo001** [comment]
Consolidating with #859
