### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by salsaman** [timmo001/system-bridge#865]
### Description

system-bridge crashes as soon as I try to run it from a terminal. It maks no difference if I try to run it as my user or as root, the same exact error is returned in both cases.

### What Platform / OS are you running?

Linux

### What version are you running?

2.7.0

### Anything in the logs or a references that might be useful?

```txt
2021-09-25 20:33:06 error: getVersion Error: Cannot read property 'trim' of undefined
2021-09-25 20:33:06 info: System Bridge 0.0.0: /usr/local/share/system-bridge/system-bridge - /home/salsaman - ["/usr/local/share/system-bridge/system-bridge","/snapshot/system-bridge/dist/index.js"] -  -  -  - 
node:internal/process/signal:36
      throw errnoException(err, 'uv_signal_start');
      ^

Error: uv_signal_start EINVAL
    at process.startListeningIfSignal (node:internal/process/signal:36:13)
    at process.emit (node:events:394:28)
    at _addListener (node:events:437:14)
    at process.addListener (node:events:491:10)
    at Object.<anonymous> (/snapshot/system-bridge/dist/index.js)
    at Module._compile (pkg/prelude/bootstrap.js:1751:22)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.runMain (pkg/prelude/bootstrap.js:1804:12) {
  errno: -22,
  code: 'EINVAL',
  syscall: 'uv_signal_start'
}
```

**Comment by salsaman** [comment]
I don't see this index.js listed amongst the package files, maybe it needs to be included in the .deb ?

**Comment by salsaman** [comment]
Confirmed here also. Version 2.6.0 produces the same error, but 2.5.0 runs without crashing (ubuntu 20.04), 64 bit.
