### ISSUE TITLE
Certain PCs crash on opening API

### ISSUE THREAD

**Issue by dlangerm** [timmo001/system-bridge#869]
### Description

A fresh install is still broken and refuses to start. Paths seem to be fixed though. There are multiple issues with the latest release though:

1. The process manager seems to be overly aggressive and keeps the process going even after selecting "Exit" on the tray. This caused a reinstall to fail multiple times before killing it via Task Manager (even then it seemed to pop up out of nowhere if I waited long enough).
2. The release version says 2.7.2 but the downloaded windows installer is installing 2.7.1 (versioning broken?)
3. The log file indicates no errors but the web portal and the API are both refusing connections

### What Platform / OS are you running?

Windows

### What version are you running?

2.7.2

### Anything in the logs or a references that might be useful?

```txt
2021-09-27 09:59:59 info: System Bridge 2.7.1: C:\Users\dlangerm\AppData\Local\System Bridge - C:\Users\dlangerm\AppData\Local\System Bridge\system-bridge.exe - C:\Users\dlangerm\AppData\Local\System Bridge - ["C:\\Users\\dlangerm\\AppData\\Local\\System Bridge\\system-bridge.exe","C:\\snapshot\\system-bridge\\dist\\index.js"] -  -  -  - 
2021-09-27 09:59:59 info: Process Manager - Starting tray - ["C:\\Users\\dlangerm\\AppData\\Local\\System Bridge\\system-bridge-tray.exe"]
2021-09-27 09:59:59 info: Process Manager - Starting api - ["C:\\Users\\dlangerm\\AppData\\Local\\System Bridge\\system-bridge.exe","dist/components/api/index.js"]
2021-09-27 10:00:01 info: Tray - 2.7.1: C:\Users\dlangerm\AppData\Local\System Bridge - C:\Users\dlangerm\AppData\Local\System Bridge\system-bridge-tray.exe - C:\Users\dlangerm\AppData\Local\System Bridge - ["C:\\Users\\dlangerm\\AppData\\Local\\System Bridge\\system-bridge-tray.exe","C:\\snapshot\\system-bridge\\tray\\dist\\index.js"] -  -  -  - 
2021-09-27 10:00:01 info: Tray - Create Tray
2021-09-27 10:00:01 info: Tray - Started
2021-09-27 10:00:31 error: Process Manager - tray: Exited with code: 1
2021-09-27 10:00:31 info: Process Manager - tray: Restarting in 10 seconds..
2021-09-27 10:00:42 info: Process Manager - Starting tray - ["C:\\Users\\dlangerm\\AppData\\Local\\System Bridge\\system-bridge-tray.exe"]
2021-09-27 10:00:43 info: Tray - 2.7.1: C:\Users\dlangerm\AppData\Local\System Bridge - C:\Users\dlangerm\AppData\Local\System Bridge\system-bridge-tray.exe - C:\Users\dlangerm\AppData\Local\System Bridge - ["C:\\Users\\dlangerm\\AppData\\Local\\System Bridge\\system-bridge-tray.exe","C:\\snapshot\\system-bridge\\tray\\dist\\index.js"] -  -  -  - 
2021-09-27 10:00:43 info: Tray - Create Tray
2021-09-27 10:00:43 info: Tray - Started
2021-09-27 10:01:58 info: System Bridge 2.7.1: C:\Users\dlangerm\AppData\Local\System Bridge - C:\Users\dlangerm\AppData\Local\System Bridge\system-bridge.exe - C:\Users\dlangerm\AppData\Local\System Bridge - ["C:\\Users\\dlangerm\\AppData\\Local\\System Bridge\\system-bridge.exe","C:\\snapshot\\system-bridge\\dist\\index.js"] -  -  -  - 
2021-09-27 10:01:59 info: Process Manager - Starting tray - ["C:\\Users\\dlangerm\\AppData\\Local\\System Bridge\\system-bridge-tray.exe"]
2021-09-27 10:01:58 info: Process Manager - Starting api - ["C:\\Users\\dlangerm\\AppData\\Local\\System Bridge\\system-bridge.exe","dist/components/api/index.js"]
2021-09-27 10:02:00 info: Tray - 2.7.1: C:\Users\dlangerm\AppData\Local\System Bridge - C:\Users\dlangerm\AppData\Local\System Bridge\system-bridge-tray.exe - C:\Users\dlangerm\AppData\Local\System Bridge - ["C:\\Users\\dlangerm\\AppData\\Local\\System Bridge\\system-bridge-tray.exe","C:\\snapshot\\system-bridge\\tray\\dist\\index.js"] -  -  -  - 
2021-09-27 10:02:00 info: Tray - Create Tray
2021-09-27 10:02:00 info: Tray - Started
```

### Additional information

If you haven't done so already, I highly recommend using the Sentry suite of tools (including the node.js sdk) for remote tracing issues like this. Uploading raw log files to a public GitHub is a bit awkward and sentry is free up to a certain number of API calls.

**Comment by timmo001** [comment]
From the logs, it looks like the tray crashed once then restarted and nothing afterwards. Does this restart loop?

I hate be the 'it works on my device' guy, but it does work on all my pcs I use day to day after the latest startup fix.


My only thought on the refused connections is maybe your firewall is blocking the API and WebSocket ports? By default these are `9170` and `9172` (TCP)

**Comment by chadmccune** [comment]
I'm experiencing the same problem

**Comment by sjdvda** [comment]
Also experiencing the same issue with 2.7.3:

`2021-09-28 10:59:52 info: Process Manager - Starting api - ["C:\\System Bridge\\system-bridge.exe","dist/components/api/index.js"]
2021-09-28 10:59:52 info: Process Manager - Starting tray - ["C:\\System Bridge\\system-bridge-tray.exe"]
2021-09-28 10:59:52 info: System Bridge 2.7.3: C:\System Bridge - C:\System Bridge\system-bridge.exe - C:\System Bridge - ["C:\\System Bridge\\system-bridge.exe","C:\\snapshot\\system-bridge\\dist\\index.js"] -  -  -  - 
2021-09-28 10:59:53 info: Tray - 2.7.3: C:\System Bridge - C:\System Bridge\system-bridge-tray.exe - C:\System Bridge - ["C:\\System Bridge\\system-bridge-tray.exe","C:\\snapshot\\system-bridge\\tray\\dist\\index.js"] -  -  -  - 
2021-09-28 10:59:53 info: Tray - Create Tray
2021-09-28 10:59:53 info: Tray - Started`

I've checked with netstat and TCPView and no processes are bound to ports 9170 and 9172

**Comment by gjeempe** [comment]
I have the same problem. I found System Bridge yesterday, installed 2.7.1 version on Windows 10 (OS Build 19042.1237)
After installation, I ran the program from start menu, a small window appeared for a moment and disappeared. 

A program icon was shown in tray menu. After clicking on it  shows that there is a new version of the program (2.7.2) but after clicking it from menu it forwarded me to 2.7.1 installer page on GitHub. 
So I tried to run settings/view data - web browser (Vivaldi) has been opened with empty page 'This site can’t be reached localhost refused to connect.'
I tried to change 'localhost' in address bar to my PC IP address (after opening ports in firewall), also tried to change localhost to 127.0.0.1 but with no luck, still ERR_CONNECTION_REFUSED occurs. 
After that I reinstalled program to new location (for example X:\SystemBridge) because I thought that system blocking connection for program installed in user/home directory - still the same problem. 

Today I found that there is a new version (2.7.3) but after installation nothing changed - still ERR_CONNECTION_REFUSED when trying to pick view data / open settings from program tray menu.

Unluckily, I can't provide any log file, because I can't find it anywhere.

**Comment by dlangerm** [comment]
Yeah, my log file is effectively empty (as shown above). It suggests the process manager restarted, but after that system bridge doesn't work at all and continuously spins up background processes (even after an uninstall, yikes).

**Comment by yousaf465** [comment]
same here,  not working for me on windows

**Comment by timmo001** [comment]
Managed to reproduce on a third machine. Running the application in powershell, an error is produced when attempting to start the API:

```bash
PS C:\Users\admin\AppData\Local\System Bridge> .\system-bridge.exe
2021-10-04 11:14:20 info: System Bridge 2.7.3: C:\Users\admin\AppData\Local\System Bridge - C:\Users\admin\AppData\Local\System Bridge\system-bridge.exe - C:\Users\admin\AppData\Local\System Bridge - ["C:\\Users\\admin\\AppData\\Local\\System Bridge\\system-bridge.exe","C:\\snapshot\\system-bridge\\dist\\index.js"] -  -  -  -
2021-10-04 11:14:20 info: Process Manager - Starting api - ["C:\\Users\\admin\\AppData\\Local\\System Bridge\\system-bridge.exe","dist/components/api/index.js"]
2021-10-04 11:14:20 info: Process Manager - Starting tray - ["C:\\Users\\admin\\AppData\\Local\\System Bridge\\system-bridge-tray.exe"]
[winston] Attempt to write logs with no transports {"message":"api error: spawn C:\\Users\\admin\\AppData\\Local\\System Bridge\\system-bridge.exe ENOENT","level":"error"}
(node:6408) UnhandledPromiseRejectionWarning: Error: spawn C:\Users\admin\AppData\Local\System Bridge\system-bridge.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:64:3)
    at Function.runMain (pkg/prelude/bootstrap.js:1805:13)
    at internal/main/run_main_module.js:17:47
(Use `system-bridge --trace-warnings ...` to show where the warning was created)
(node:6408) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:6408) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2021-10-04 11:14:27 info: Tray - 2.7.3: C:\Users\admin\AppData\Local\System Bridge - C:\Users\admin\AppData\Local\System Bridge\system-bridge-tray.exe - C:\Users\admin\AppData\Local\System Bridge - ["C:\\Users\\admin\\AppData\\Local\\System Bridge\\system-bridge-tray.exe","C:\\snapshot\\system-bridge\\tray\\dist\\index.js"] -  -  -  -
2021-10-04 11:14:27 info: Tray - Create Tray
2021-10-04 11:14:27 info: Tray - Started
```

**Comment by timmo001** [comment]
```bash
2021-10-04 13:11:10 info: System Bridge 2.7.4: C:\Users\admin\AppData\Local\System Bridge - C:\Users\admin\AppData\Local\System Bridge\system-bridge.exe - C:\Users\admin\AppData\Local\System Bridge - ["C:\\Users\\admin\\AppData\\Local\\System Bridge\\system-bridge.exe","C:\\snapshot\\system-bridge\\dist\\index.js"] -  -  -  -
2021-10-04 13:11:10 info: Process Manager - Starting api - ["C:\\Users\\admin\\AppData\\Local\\System Bridge\\system-bridge.exe","dist/components/api/index.js"]
2021-10-04 13:11:12 info: Process Manager - Starting tray - ["C:\\Users\\admin\\AppData\\Local\\System Bridge\\system-bridge-tray.exe"]
[winston] Attempt to write logs with no transports {"message":"api error: spawn C:\\Users\\admin\\AppData\\Local\\System Bridge\\system-bridge.exe ENOENT","level":"error"}
2021-10-04 13:11:12 error: Process Manager - Uncaught Exception: Error: spawn C:\Users\admin\AppData\Local\System Bridge\system-bridge.exe ENOENT
2021-10-04 13:11:16 info: Tray - 2.7.4: C:\Users\admin\AppData\Local\System Bridge - C:\Users\admin\AppData\Local\System Bridge\system-bridge-tray.exe - C:\Users\admin\AppData\Local\System Bridge - ["C:\\Users\\admin\\AppData\\Local\\System Bridge\\system-bridge-tray.exe","C:\\snapshot\\system-bridge\\tray\\dist\\index.js"] -  -  -  -
2021-10-04 13:11:16 info: Tray - Create Tray
2021-10-04 13:11:18 info: Tray - Started
```

**Comment by timmo001** [comment]
```bash
PS C:\Users\admin\AppData\Local\System Bridge> .\system-bridge.exe
2021-10-05 14:13:54 info: System Bridge 2.7.4: C:\Users\admin\AppData\Local\System Bridge - C:\Users\admin\AppData\Local\System Bridge\system-bridge.exe - C:\Users\admin\AppData\Local\System Bridge - ["C:\\Users\\admin\\AppData\\Local\\System Bridge\\system-bridge.exe","C:\\snapshot\\system-bridge\\dist\\index.js"] -  -  -  -
2021-10-05 14:13:54 info: Process Manager - Starting api - ["C:\\Users\\admin\\AppData\\Local\\System Bridge\\system-bridge.exe","dist/components/api/index.js"]
2021-10-05 14:13:54 info: Process Manager - Starting tray - ["C:\\Users\\admin\\AppData\\Local\\System Bridge\\system-bridge-tray.exe"]
2021-10-05 14:13:54 error: Process Manager - api error: spawn C:\Users\admin\AppData\Local\System Bridge\system-bridge.exe ENOENT
(node:7840) UnhandledPromiseRejectionWarning: Error: spawn C:\Users\admin\AppData\Local\System Bridge\system-bridge.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:64:3)
    at Function.runMain (pkg/prelude/bootstrap.js:1805:13)
    at internal/main/run_main_module.js:17:47
(Use `system-bridge --trace-warnings ...` to show where the warning was created)
(node:7840) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:7840) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2021-10-05 14:14:00 info: Tray - 2.7.4: C:\Users\admin\AppData\Local\System Bridge - C:\Users\admin\AppData\Local\System Bridge\system-bridge-tray.exe - C:\Users\admin\AppData\Local\System Bridge - ["C:\\Users\\admin\\AppData\\Local\\System Bridge\\system-bridge-tray.exe","C:\\snapshot\\system-bridge\\tray\\dist\\index.js"] -  -  -  -
2021-10-05 14:14:00 info: Tray - Create Tray
2021-10-05 14:14:02 info: Tray - Started
```

**Comment by timmo001** [comment]
The issue was the API was being attempted to be launched with `execa.node` instead of launching the prebuilt system-bridge.exe which has node built in.

On my (dev) machines, I have node installed, but on other machines, this may not be the case. Now node will not be required as it should have been and the API will be launched as a subprocess alongside the tray (if enabled)
